---
instance:
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/returnfloat/homelab.git"
    pullSecret: github-deploy-key
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
