---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nocodb-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # nocodb
        NC_AUTH_JWT_SECRET: "{{ .NOCODB_AUTH_JWT_SECRET }}"
        NC_PUBLIC_URL: "https://nocodb.{{ .HOMELAB_SECRET_DOMAIN }}"
        NC_DB: "pg://{{ .POSTGRESQL_HOST }}:5432?u={{ .NOCODB_POSTGRESQL_USER }}&p={{ .NOCODB_POSTGRESQL_PASS }}&d={{ .NOCODB_POSTGRESQL_DB }}"
        NC_REDIS_URL: "redis://:{{ .REDIS_PASSWORD }}@{{ .REDIS_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_NOCODB_DB }}"
        NC_ADMIN_EMAIL: "{{ .NOCODB_ADMIN_EMAIL }}"
        NC_ADMIN_PASSWORD: "{{ .NOCODB_ADMIN_PASSWORD }}"
        NC_SMTP_SECURE: "true"
        NC_SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        NC_SMTP_PORT: "{{ .HOMELAB_SMTP_SSL_PORT }}"
        NC_SMTP_FROM: "{{ .HOMELAB_SMTP_USERNAME }}"
        NC_SMTP_USERNAME: "{{ .HOMELAB_SMTP_USERNAME }}"
        NC_SMTP_PASSWORD: "{{ .HOMELAB_SMTP_PASS }}"
        # postgres init
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .NOCODB_POSTGRESQL_DB }}"
        INIT_POSTGRES_USER: "{{ .NOCODB_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .NOCODB_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: nocodb-external-secret
