---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drawio
  namespace: utilities
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      drawio:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jgraph/drawio
              tag: 27.1.6
            env:
              LETS_ENCRYPT_ENABLED: "false"
              PUBLIC_DNS: "draw.${SECRET_DOMAIN}"
              DRAWIO_BASE_URL: "https://draw.${SECRET_DOMAIN}"
              DRAWIO_SERVER_URL: "https://draw.${SECRET_DOMAIN}"
              DRAWIO_VIEWER_URL: "https://draw.${SECRET_DOMAIN}/js/viewer.min.js"
              DRAWIO_LIGHTBOX_URL: "https://draw.${SECRET_DOMAIN}/."
    service:
      app:
        controller: drawio
        ports:
          http:
            port: 8080
          https:
            port: 8443
    route:
      app:
        hostnames: ["draw.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
    # ingress:
    #   app:
    #     enabled: true
    #     className: internal
    #     annotations:
    #       # external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    #       nginx.ingress.kubernetes.io/auth-url: |-
    #         http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    #       nginx.ingress.kubernetes.io/auth-signin: |-
    #         https://draw.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
    #       nginx.ingress.kubernetes.io/auth-response-headers: |-
    #         Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
    #       nginx.ingress.kubernetes.io/auth-snippet: |
    #         proxy_set_header X-Forwarded-Host $http_host;
    #     hosts:
    #       - host: &host "draw.${SECRET_DOMAIN}"
    #         paths:
    #         - path: /
    #           pathType: Prefix
    #           service:
    #               identifier: app
    #               port: http
    #     tls:
    #       - hosts:
    #           - *host

