---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-redis
  namespace: databases
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 21.2.12
      sourceRef:
        kind: HelmRepository
        name: bitnami-redis
        namespace: databases
      interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
  values:
    architecture: standalone
    commonAnnotations:
      secret.reloader.stakater.com/reload: "redis-external-secret"
    auth:
      enabled: true
      sentinel: true
      existingSecret: redis-external-secret
      existingSecretPasswordKey: REDIS_PASSWORD
      usePasswordFiles: false
      usePasswordFileFromSecret: false
    sentinel:
      enabled: false
      masterSet: redis-master
    master:
      disableCommands: []
      # disableCommands: ["FLUSHDB","FLUSHALL"]
      persistence:
        enabled: false
    replica:
      disableCommands: []
      # disableCommands: ["FLUSHDB","FLUSHALL"]
      persistence:
        enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

