---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 20.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
  values:
    architecture: standalone
    commonAnnotations:
      secret.reloader.stakater.com/reload: "redis-external-secret"
    auth:
      enabled: true
      sentinel: true
      existingSecret: redis-external-secret
      existingSecretPasswordKey: REDIS_PASSWORD
    sentinel:
      enabled: false
      masterSet: redis-master
    master:
      disableCommands: []
      # disableCommands: ["FLUSHDB","FLUSHALL"]
      persistence:
        enabled: false
    replica:
      disableCommands: []
      # disableCommands: ["FLUSHDB","FLUSHALL"]
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

