---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-redis
  namespace: databases
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
