---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-external-secret
        property: REDIS_PASSWORD
  dataFrom:
    - extract:
        key: redis-external-secret
