---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  - ./helmrelease.yaml
  - ./tandoor-configmap.yaml
  - ./tandoor-external-secret.yaml
  - ./tandoor-pvc.yaml
