---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-pvc
  namespace: utilities
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
