---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatgpt-next-web-external-secret
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # chatgpt-next-web
        CODE: "{{ .CHATGPT_NW_ACCESS_CODE }}"
        OPENAI_API_KEY: "{{ .CHATGPT_NW_OPENAI_API_KEY }}"
        OPENAI_ORG_ID: "{{ .CHATGPT_NW_OPENAI_ORG_ID }}"
        GOOGLE_API_KEY: "{{ .CHATGPT_NW_GOOGLE_API_KEY }}"
        # HIDE_USER_API_KEY: "1"
        # DISABLE_GPT4: "1"
        CUSTOM_MODELS: "-gpt-4-0125-preview,-gpt-4-0314,-gpt-4-0613,-gpt-4-32k-0314,-gpt-4-32k-0613,-gpt-4-1106-preview,-gpt-4-vision-preview,-gpt-3.5-turbo-0301,-gpt-3.5-turbo-0613,-gpt-3.5-turbo-1106,-gpt-3.5-turbo-16k-0613,-gpt-3.5-turbo-0125"
  dataFrom:
    - extract:
        key: chatgpt-next-web-external-secret
