---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chatgpt-next-web
  namespace: automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      chatgpt-next-web:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret chatgpt-next-web-external-secret
        containers:
          app:
            image:
              repository: yidadaa/chatgpt-next-web
              tag: v2.12.2
            envFrom:
              - secretRef:
                  name: *secret
    service:
      app:
        controller: chatgpt-next-web
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "ai.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

