---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
resources:
  - ./helmrelease.yaml
  - ./teslamate-external-secret.yaml
  - ./teslamate-grafana-datasource.yaml
  - ./dashboards
