---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_ENCRYPTION_KEY
    - secretKey: DATABASE_USER
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_DATABASE_USER
    - secretKey: DATABASE_PASS
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_DATABASE_PASS
    - secretKey: DATABASE_NAME
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_DATABASE_NAME
    - secretKey: DATABASE_HOST
      remoteRef:
        key: postgresql-external-secret
        property: POSTGRESQL_HOST
    - secretKey: MQTT_HOST
      remoteRef:
        key: mosquitto-external-secret
        property: MOSQUITTO_HOST
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_MQTT_USERNAME
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: teslamate-external-secret
        property: TESLAMATE_MQTT_PASSWORD
    # Postgres Init
    - secretKey: INIT_POSTGRES_HOST
      remoteRef:
        key: postgresql-external-secret
        property: POSTGRESQL_HOST
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
          key: postgresql-external-secret
          property: POSTGRESQL_SUPERUSER_PASS
    - secretKey: INIT_POSTGRES_DBNAME
      remoteRef:
          key: teslamate-external-secret
          property: TESLAMATE_DATABASE_NAME
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
          key: teslamate-external-secret
          property: TESLAMATE_DATABASE_USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
          key: teslamate-external-secret
          property: TESLAMATE_DATABASE_PASS
  dataFrom:
    - extract:
        key: mosquitto-external-secret
    - extract:
        key: postgresql-external-secret
    - extract:
        key: teslamate-external-secret
