---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rxresume-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # rxresume
        DISABLE_SIGNUPS: "true"
        DISABLE_EMAIL_AUTH: "true"
        ACCESS_TOKEN_SECRET: "{{ .RXRESUME_ACCESS_TOKEN_SECRET }}"
        REFRESH_TOKEN_SECRET: "{{ .RXRESUME_REFRESH_TOKEN_SECRET }}"
        STORAGE_URL: "https://minio.{{ .HOMELAB_SECRET_DOMAIN }}/rxresume"
        STORAGE_ENDPOINT: "minio.{{ .HOMELAB_SECRET_DOMAIN }}"
        STORAGE_USE_SSL: "true"
        STORAGE_PORT: "443"
        STORAGE_BUCKET: "rxresume"
        STORAGE_ACCESS_KEY: "{{ .RXRESUME_MINIO_STORAGE_ACCESS_KEY }}"
        STORAGE_SECRET_KEY: "{{ .RXRESUME_MINIO_STORAGE_SECRET_KEY }}"
        TOKEN: "{{ .RXRESUME_CHROME_TOKEN }}"
        CHROME_TOKEN: "{{ .RXRESUME_CHROME_TOKEN }}"
        DATABASE_URL: "postgresql://{{ .RXRESUME_POSTGRESQL_USER }}:{{ .RXRESUME_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST }}:{{ .POSTGRESQL_PORT }}/{{ .RXRESUME_POSTGRESQL_DBNAME }}"
        SMTP_URL: "smtp://{{ .HOMELAB_SMTP_USERNAME }}:{{ .HOMELAB_SMTP_PASS }}@{{ .HOMELAB_SMTP_HOST }}:{{ .HOMELAB_SMTP_PORT }}"
        MAIL_FROM: "{{ .HOMELAB_SMTP_USERNAME }}"
        # OpenID
        VITE_OPENID_NAME: "Authentik"
        OPENID_AUTHORIZATION_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/authorize/"
        OPENID_CALLBACK_URL: "https://rxresume.{{ .HOMELAB_SECRET_DOMAIN }}/api/auth/openid/callback"
        OPENID_CLIENT_ID: "{{ .RXRESUME_OIDC_CLIENT_ID }}"
        OPENID_CLIENT_SECRET: "{{ .RXRESUME_OIDC_CLIENT_SECRET }}"
        OPENID_ISSUER: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/rxresume/"
        OPENID_SCOPE: "openid profile email"
        OPENID_TOKEN_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/token/"
        OPENID_USER_INFO_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/userinfo/"
        PUBLIC_URL: "http://rxresume.{{ .HOMELAB_SECRET_DOMAIN }}"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .RXRESUME_POSTGRESQL_DBNAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .RXRESUME_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .RXRESUME_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: rxresume-external-secret
