---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rxresume-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # rxresume
        ACCESS_TOKEN_SECRET: "{{ .RXRESUME_ACCESS_TOKEN_SECRET }}"
        REFRESH_TOKEN_SECRET: "{{ .RXRESUME_REFRESH_TOKEN_SECRET }}"
        STORAGE_URL: "http://minio.storage:9000/rxresume"
        STORAGE_ACCESS_KEY: "{{ .RXRESUME_MINIO_STORAGE_ACCESS_KEY }}"
        STORAGE_SECRET_KEY: "{{ .RXRESUME_MINIO_STORAGE_SECRET_KEY }}"
        TOKEN: "{{ .RXRESUME_CHROME_TOKEN }}"
        CHROME_TOKEN: "{{ .RXRESUME_CHROME_TOKEN }}"
        DATABASE_URL: "postgresql://{{ .RXRESUME_POSTGRESQL_USER }}:{{ .POSTGRESQL_SUPERUSER_PASS }}@{{ .POSTGRESQL_HOST }}:{{ .POSTGRESQL_PORT }}/{{ .RXRESUME_POSTGRESQL_DBNAME }}"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .RXRESUME_POSTGRESQL_DBNAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .RXRESUME_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .RXRESUME_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: rxresume-external-secret
