# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:uXkZt5o80bwMJl8xTnQile4zhI7+NnZ7OS4ow+TKJ31FIHXBn0NWMQC2yxH8CWJVjS8U/Wf+eJ2FxRkaxd8Jj2b2nxrVty//F4x3Z/hguvodplj8qKADRzk7FcDOYk2IAEXTl6ztdV7N6JuGlZ9bYST3zR1iu/jKsrVKF2F9EzQtuDrzXEg9gZlYGzgpcTjnghQ1jHJGspXcQwVwrQGw+KdaaesL5J8rTC7bD4UAmw==,iv:iOCwOjrSwuJ9Ex9y7A7Ax1fsOeem7QCFTRuvhQLcWCw=,tag:LJj2bBKqbymp1icGo0a8jA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYk5TRFUrUzMzWjFvb0k5
        MjBMZXVQbGNXWmw2cUZIOFh3UXZVeEYxYjJrCkZPbHNyYXF0eTBINEM2NjRMYU52
        bEFiWUtVR1RxR0M2aStWc09nVzVIS3MKLS0tIDFlYzZnVFdxSEJ0UW5oQ0J6bXZV
        V0NlR3pPRndmZUVyVnVDenhMeXo3Z0EK5heaQfxLkBWtoCenZxGk4AqQ1w6+yZoK
        +qPOfApfvDmMmWUhEP6IStyNHon99qH7zXSgkGWaHjUuYv/wjkamdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T23:50:17Z"
  mac: ENC[AES256_GCM,data:Wzi5GH20DInvopuEqAUe3T78s1EkCsPpLKMolQ6gKaCzksBkS0KRWOrlxFxHPqyEWKznt18EQH16h0OrEDZ2eZX+6fKpDFngKq7MH/g+BJ6XpRWGBaWj6G+nCLO4zwpLs0t2iQofmwa2evOzgxjSXmli7EpKBRghKsCWCcCQruI=,iv:8UVd6VCB5Ya/9vE/pJ6KGX4+ogquE+jZmBHkC6ZAN8Y=,tag:9VczIS7tXgQtgQ8suO75nA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
