# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:9Y4wCMUKmloOKv+SAk3a7bQ1EBunXrLJ6c2/UYQkFutVfZGXiV8Guz9dglACV+4Jjlp66MBlwhr5HcLyw1COkRvkzrst2fpUeEagIcSVHpM1FmS482IH9CwLDSpfHYHg9EGd6CaBG0+R9ca4EDSbXVLtOK0g2Tn39AdyX2wzDC/2itqdhUqnAAaPPjfkFcv2Gy8mPMNxnZ/azTc1s8m13e+aJjfhteQaEZ6Q6ISEWQ==,iv:5p1A0OtjEF6skF0if5uSoI39ha7Ogx4VKY3g649jjdI=,tag:vlVxb4rLoS+kPDey+8DwvA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK1JoUkU2eE5kbzZBMHU5
        djhZRW8vZTFCM3ljTnhUZ1BUc0UrRG90eEVrCnc4Y1ZUekd0UkljUk9QcW8waDM2
        WnVyd1p1cUlaSVk5QTF5N0dmaU9zWFEKLS0tIGRaYnNMWkpEMXZSbkY3UURaSXBs
        Snk1K20wUGRnVFAyQVorZ21JcFc1d3MK1pMuEqhYcSCAXVjgOVyRJZ/PIYvsxiRl
        zCIvUczlv+x1BU+xqazH5/Pjy/7b7NUyRbdolkgCZsVvHNSEaH0A1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T23:25:21Z"
  mac: ENC[AES256_GCM,data:pfu9ijemb2rm6WyQquXgQNEBDdsOnXrmOiwJIeh+OLdjhNxMF2iiGeAoLdCqxERX2oU7RLstTed9vwLIakB10E5R0HAJsVUtfG297xDJu+ZBsRZ2XYI9+3cWzE03xGvp9TirUZL0Uw5gD1nZf2k+PjLYKgUwflihclihJuWCwuQ=,iv:sIWMNVYGtAxNQBxs7NKN03VC5N+SP6c5NYU+XgBMmbI=,tag:/pocIfVEtuumVyJUOyQzpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
