---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kavita/ks.yaml
  - ./miniflux/ks.yaml
  - ./stash/ks.yaml
  - ./immich/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: media
    target:
      kind: Namespace
