---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cyberchef/ks.yaml
  - ./teslamate/ks.yaml
  - ./nginx-static/ks.yaml
  - ./paperless/ks.yaml
  - ./outline/ks.yaml
  - ./vikunja/ks.yaml
  - ./drawio/ks.yaml
  - ./rxresume/ks.yaml
  - ./hoarder/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: utilities
    target:
      kind: Namespace
