---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cyberchef/ks.yaml
  - ./teslamate/ks.yaml
  # - ./tandoor/ks.yaml
  - ./nginx-static/ks.yaml
  # - ./paperless/ks.yaml
  - ./outline/ks.yaml
  - ./drawio/ks.yaml

