---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-minio
  namespace: storage
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
