---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 15.0.3
  interval: 30m0s
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: bitnami/minio
      tag: 2025.2.7
      pullPolicy: IfNotPresent
    podAnnotations:
      secret.reloader.stakater.com/reload: "minio-external-secret"
      prometheus.io/scrape: "true"
      prometheus.io/path: "/minio/v2/metrics/cluster"
      prometheus.io/port: "9000"
    mode: standalone
    auth:
      existingSecret: minio-external-secret
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001
    ingress:
      enabled: true
      ingressClassName: internal
      hostname: "minio-console.${SECRET_DOMAIN}"
      tls: true
    apiIngress:
      enabled: true
      ingressClassName: external
      annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hostname: "minio.${SECRET_DOMAIN}"
      tls: true
    persistence:
      enabled: true
      storageClass: nfs-csi
      accessModes: ["ReadWriteOnce"]
      size: 20Gi
    volumePermissions:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: false
    podSecurityContext:
      enabled: true
      fsGroup: 100
    containerSecurityContext:
      enabled: true
      runAsUser: 1026
      runAsNonRoot: true
