---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-minio
  namespace: storage
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-minio
        namespace: storage
      version: 16.0.10
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: bitnami/minio
      tag: 2025.4.22
      pullPolicy: IfNotPresent
    podAnnotations:
      secret.reloader.stakater.com/reload: "minio-external-secret"
      prometheus.io/scrape: "true"
      prometheus.io/path: "/minio/v2/metrics/cluster"
      prometheus.io/port: "9000"
    mode: standalone
    auth:
      existingSecret: minio-external-secret
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001
    # ingress:
    #   enabled: true
    #   ingressClassName: internal
    #   hostname: "minio-console.${SECRET_DOMAIN}"
    #   tls: true
    # apiIngress:
    #   enabled: true
    #   ingressClassName: external
    #   annotations:
    #       external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    #   hostname: "minio.${SECRET_DOMAIN}"
    #   tls: true
    persistence:
      enabled: true
      storageClass: nfs-csi
      accessModes: ["ReadWriteOnce"]
      size: 20Gi
    volumePermissions:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: false
    podSecurityContext:
      enabled: true
      fsGroup: 100
    containerSecurityContext:
      enabled: true
      runAsUser: 1026
      runAsNonRoot: true
