# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+F415oEhe9YodOne9VsXFEK0nLjV4dttJPazNrZ16Ts=,iv:JH4uhcGBsS5w28+ue/pewpDsnJkGuMHA4Wqs6v4WLik=,tag:DpViDhU9UtU6a+i9jcZ9Bw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUWl3TVJaTFJ3eDU5dk1p
        ZzZFUkpEVkdGNEljNVdGMGdnT1haME9iTlI4CnY4N3poeVd2V0dZY2VBbHZDNllx
        ME5DYTFHbUhFWGI2SWN5cEVKUU9SWGsKLS0tIE5VWkZLR3NqWWdFUW41RzI5aW9u
        RThEUDUzcUpsUW16a1R3RXlEaVBKZVEKP1axsIEfrWTjYi7hyejrZhJYinXxlLcc
        zyt+w+foYoFzFscPzZNai+9OuvyGyYn85F0zB69xOtujY1+TGPT10Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:32:28Z"
  mac: ENC[AES256_GCM,data:K8wd2r5zKqBb9rtOoCMJP+yiruGEEnyzgapwRWIUMHzFn2QHHkc31TbbNtWHx9nvI94TtS1rx7w8fag0+CzoGy9C3umGbMFERy+Jv0f24u6qi0Dcvb/7QlkM1fVJUZj5emY/Y1xAtumpVVhFb8enXOL5eGZY05s5dTKUlqlPlSY=,iv:smtO+IovbVDLRn2a6yiEzx5QDULLwkBku7/fCf+NNFI=,tag:EOxanzYVOnPrLIJAdl3YgQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
