# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AEn1fB+8DLF/+5YXZYP17kq4PGDWsCgqEsv0ImCyO2U=,iv:rg0J6AF/UXYqZdXtnzActIXkRr82t/1rSsBuAs1IqG4=,tag:B23LkTAchTrtwbQlvWMZoQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dDZCN2dsRUg4Q0xOQ3Y2
        cDFVWFlXU29CNU9zTnpDdE5IUVovQUZLUlRBClo1RUU1MkluMmQzOWNmdjhaL0hJ
        dzhtQjcyelp2SXJBMDJYcCt2SU1aR2sKLS0tIFlLSG1lT0w5WHlaa2FBVnVCeXJW
        YTNMd2tDZDhJRkF5ZStUNVhFbkJxamMKXf62YrLhsj83RL5Yzx8+BPQmwr6dvrHm
        5Rl0zpHtRAdLkN2pM+GzI3mcuWOERVEOqoKMozhw5nIOVc7DTx9gFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T02:36:19Z"
  mac: ENC[AES256_GCM,data:5/OQBWgOSwXEDI2a3xa8Fzy92JeWO5MhPISHo+cLJ31nQs2CiQgVRUa8uNzqn/LlE4jGPpn2bWuLuOcnz9KEycwDvBMYz52PnyfWLOlBJg8psB+xqTDvheNxcb4BIcBQZvgAJEPN/LJ6F9+nVBDq7PcdawQKKfKIPWuLHhK/UEo=,iv:Jy+FD4LgOW0PaQVVZ6X7KMcNMTkgyvoIusGKrRF0QdY=,tag:Z3VtWrMznFPQZLKaVb34qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
