# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rluobUtsNXdeLGqvHDFCWt4uc7Tmes7CkGtaQgn2LY++HDNZIXfnZw==,iv:zE9xTM492OeIZJ5kiq5pmXf1LUPlWgbtBEHK//mP1/I=,tag:rFpdZDYrfwUAmOCByOA42w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVFyS0NmVWRBa2NnQkpK
        VVFKNjJpaWU4RkJxVGFQejZ2VHBzcmV4UFRZClNocisrSmhuMlYxY3NrNEh2VlhG
        bFZlV24rZXRVcVhmc0NPOE1Vbk02U0UKLS0tIHVOWnNNSFZJMmhjQUlwTmlBb1FP
        ZG1RSFk4UEdRSTVJbzNHeUIrbW8xQWMKVEeqOxHtnWUV4hgC4FkiKdlKBAh7z8rd
        g2Fqw1x7Qk9iu3f7VQYP5KAygS0p4ku5jKRazLq7d4k8McAfdRMu2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-10T23:13:52Z"
  mac: ENC[AES256_GCM,data:S6zSeIoNwxrXc1fJigkiJEP6bslRQ73cbBwCK5265P4Zl77soqFEVKJ121B9Bq4yZdkl2rbY0t4oci946/y7E0zu2G/YfuZnKRNPIp/lt37I+joQ2snSmSnkG64gZgPnWltLx9H3xY+jPZPl8pQcflPGPlNJDu5Tq1uaTdp37Zg=,iv:wrA1IQXrrMRUNorLpTngt+9OjS790gyTRipSyVI4X5g=,tag:W1E+437emJrLTkpX9iiinQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
