# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TaRhldbsDAvBDhw1sfu6mJkxPfkMJtjkbTt8lMSaLW7o2jI3mXye1Q==,iv:3Yw0qWsbsA+vikNew+C7BDxaFOjaIKoLigOtwVKC0mE=,tag:I/PTXmLsyZuz9t6qQV9Kww==,type:str]
sops:
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM2RLVlovTmVzazduWmIw
        YTdhVzRLOS9jbldDM3BlbTZkalRRWCt2bncwCnQyWmxqUkJvbnVwOWg3T0JESDV6
        eTRzVE5RL3ZkdDNPcGhoa1FuUGFBeE0KLS0tIE90RERTMklpTlZUaGx0NGxZVHEy
        MzF3K1dwYWt5dkdmcndaeG9rZE02R0EKdOR//wdJA+AoxaTdH8uqd5aDtC4KKiA2
        tqLXNXwlo3iIZ8s3dEQQcM/Od/3JCt5fEW5cpCMpOL3eUCWaxoU6Cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T20:42:33Z"
  mac: ENC[AES256_GCM,data:uEoFCq11gvaub3VhB4cwkijiWpFmY88yxGpBlpa2QUi61+BQbLkMPm1pJb2S1bjs9UhY22RGDTrnGhActyYL57sh59ACl5cAePMmMoUVBIKqwKhVeu7vJtO4Cg4k1Shj7JtP7qfGgVsfq8oLEgS5ANjWHpgnIt1MVwzfG37YODY=,iv:Ns/KeYy1raVxe0yt0RwRSUKrHMxcdpoCIUSnJWgYLO0=,tag:dsrxjVGO7+B581YLPMqxvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
