---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
  data:
    - secretKey: username
      remoteRef:
        key: postgresql-external-secret
        property: POSTGRESQL_SUPERUSER_USER
    - secretKey: password
      remoteRef:
        key: postgresql-external-secret
        property: POSTGRESQL_SUPERUSER_PASS
  dataFrom:
    - extract:
        key: postgresql-external-secret
