---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karakeep
  namespace: utilities
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: karakeep
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      karakeep:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret karakeep-external-secret
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.27.1
              pullPolicy: IfNotPresent
            env:
              DATA_DIR: "/data"
              MEILI_ADDR: "http://karakeep-meilisearch:7700"
              BROWSER_WEB_URL: "http://karakeep-chrome:9222"
              NEXTAUTH_URL: "https://karakeep.${SECRET_DOMAIN}"
              OAUTH_PROVIDER_NAME: Authentik
              DISABLE_PASSWORD_AUTH: "true"
            envFrom:
              - secretRef:
                  name: *secret
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.20.0
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secretRef:
                  name: *secret
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
    service:
      app:
        controller: karakeep
        ports:
          http:
            port: &port 3000
      chrome:
        controller: karakeep
        ports:
          http:
            port: 9222
      meilisearch:
        controller: karakeep
        ports:
          http:
            port: 7700
    route:
      app:
        hostnames: ["karakeep.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 10Gi
        retain: true
        advancedMounts:
          karakeep:
            app:
              - path: /data
                subPath: data
                readOnly: false
            meilisearch:
              - path: /meili_data
                subPath: meili_data
                readOnly: false
