---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # karakeep
        NEXTAUTH_SECRET: "{{ .KARAKEEP_NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .KARAKEEP_MEILI_MASTER_KEY }}"
        OPENAI_API_KEY: "{{ .KARAKEEP_OPENAI_API_KEY }}"
        OAUTH_WELLKNOWN_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/karakeep/.well-known/openid-configuration"
        OAUTH_CLIENT_ID: "{{ .KARAKEEP_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .KARAKEEP_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: karakeep-external-secret
