---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: baserow-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # baserow
        BASEROW_PUBLIC_URL: "https://baserow.{{ .HOMELAB_SECRET_DOMAIN }}"
        BASEROW_MAX_IMPORT_FILE_SIZE_MB: "64"
        SECRET_KEY: "{{ .BASEROW_SECRET_KEY }}"
        BASEROW_JWT_SIGNING_KEY: "{{ .BASEROW_JWT_SIGNING_KEY }}"
        BASEROW_BACKEND_LOG_LEVEL: "INFO"
        BASEROW_BACKEND_DATABASE_LOG_LEVEL: "ERROR"
        DATABASE_HOST: &dbhost "{{ .POSTGRESQL_HOST }}"
        DATABASE_PORT: "{{ .POSTGRESQL_PORT }}"
        DATABASE_NAME: &dbname "{{ .BASEROW_POSTGRESQL_DB }}"
        DATABASE_USER: &dbuser "{{ .BASEROW_POSTGRESQL_USER }}"
        DATABASE_PASSWORD: &dbpass "{{ .BASEROW_POSTGRESQL_PASS }}"
        REDIS_HOST: "{{ .REDIS_HOST }}"
        REDIS_PORT: "{{ .REDIS_PORT }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        FROM_EMAIL: "{{ .HOMELAB_SMTP_USERNAME }}"
        EMAIL_SMTP: "true"
        EMAIL_SMTP_USE_TLS: "true"
        EMAIL_SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        EMAIL_SMTP_PORT: "{{ .HOMELAB_SMTP_PORT }}"
        EMAIL_SMTP_USER: "{{ .HOMELAB_SMTP_USERNAME }}"
        EMAIL_SMTP_PASSWORD: "{{ .HOMELAB_SMTP_PASS }}"
        # postgres init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: baserow-external-secret
