# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app baserow
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: postgresql-bitnami
      namespace: databases
    - name: redis
      namespace: databases
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret baserow-external-secret
        initContainers:
          01-initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
            envFrom:
              - secretRef:
                  name: *secret
          02-chown-data:
            image:
              repository: busybox
              tag: latest
            command: ["sh", "-c", "chown -R 9999:9999 /baserow/data"]
            securityContext:
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["all"]
                add: ["CHOWN", "CHMOD"]
              runAsUser: 0
              runAsNonRoot: false
        containers:
          main:
            image:
              repository: baserow/baserow
              tag: 1.22.3
            envFrom:
              - secretRef:
                  name: *secret
    service:
      main:
        ports:
          http:
            port: 80
          https:
            port: 443
    ingress:
      main:
        enabled: true
        primary: true
        className: internal
        hosts:
          - host: &host "baserow.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        retain: true
        size: 20Gi
        globalMounts:
          - path: /baserow/data
            readOnly: false
