apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:NdPOwFpkU2DLpI/S0Lt+3yAV4NkU0DOIFBRDHgGXKRI2zgaF,iv:N8n9xvLO8I2CrKhOJ0x69Si5a/HlavpnIL26VsJipQU=,tag:8GdoJL9IhmxQoptHmdZ6Tw==,type:str]
    credentials.json: ENC[AES256_GCM,data:QpCic96ShX+JblRHG9liwOiV6EAcFL8tXBUK3hZRpSAwZYvZ+OhO1nvBDcav8/xrKYJ/X5JECkCZ+3IFkJwWK67Q3CmLgnUAf8cFBMHyGy3VZM0MVdokE2HCHeaHHuIoNseHbX2PnbwFX9mnumXoKUUH2u65HzA+ca73R/a4f3VnAtXc+kj8Cw0Nesaksy5TZgD3xgjV7JJf389aO+HBeEHzSbfYGnhZ+r/TG53HnA==,iv:mwLwY2F3M0fJx3f/6bN+mRnV3e/bhUu3hTfRMyrBC8w=,tag:9SH+B0GfBoYu32hApUOkPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOGVjc3JDOGlxOUFoWlli
            eXd1UStGOWlmZFhCKzI5d0prUkt0ZWNYdkNVCkVkVlBXOU1YMmNyNHQ2Mmc1V25X
            TUgxQmdJQXQwTUxBMUJoQWVWMEZla3MKLS0tIDFpNEZzTkdrUDRCbkp3eFBDRHVt
            cUVua2lueW1lRm1iaEZSVmpQMmk2UmsKkBXyNvl6WxfOchTY+kHd5ww5F71OK8zy
            t5cRp1SzMF55ZWMkhUt2n/O6TiZ7l/2sC55Tn7vTTKpbVoWWnsUOTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T03:53:21Z"
    mac: ENC[AES256_GCM,data:V0DfXfCvUJlIUm0COdoGC/spei0DTQxGkqzY+GI9Zck+1K0Yf1nsy+WcN9JA6DPVvIyZiof9x2aACfJixP+TRcWcsst4Rt7tvJrnEu+l1knfLe+yeHAuxGl0wNVHi8SdwZ16MAyFKw9Jefopqpni1oe7nY5xwJorzTm5ppZUha4=,iv:CDYQRc5AVm5Fup9LIL1p4ZUHKUIsKlpiL6npurXpMaU=,tag:kukG0AczAcMr8CmvPfWQIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
