apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:p5GLp9pVxy8tdI0F7NXAuQd9ectBmKIVRR1XE5Gi0HK159Kd,iv:36qoKHF051GWDEV1rn6Uzg2XqA2QUtbaqm0WwHseRzU=,tag:MdoHYLYyx7NeTWX50nRyzg==,type:str]
    credentials.json: ENC[AES256_GCM,data:GpL6GCLS5lEaxe9fr3GqIuJ0uPMjlPhZM5jqxcNq1r7XUHWBlDFhK4H1RL+5CmZqXfWFqWnaxGqzbmvmggFDN+9AaFd0KKOJy47/fde/gmwE+Mlk3PalXnmeOjv31LbgCjm+YPTffXMgkKbOGnLdEiLFN8ZYjCFkbKuBRsrKr+5PhyPB8iMBdhntELi78tTAJAlO0xkM7eLgeaQwCh3WkBomAXHhAV10nH2LJ+YRBA==,iv:3a3JD7Pk1ERVn0M+jd+ibTy5YJtj0Cj2+5x1VNcnWgQ=,tag:XD3nmd1bsBf+7JeqIkYcEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaDM2alZiTkNjL1ZIakFV
            a0hlT2NqS1ByN2xFZGh0TERLKytCa0UrN2lZCjhoRVJYUVo1bzZSRkVmblhQcVY5
            Z1FhSnlZZXFBVVhuVkVYajBNbXBtRTgKLS0tIHo5VGZ1SUkra2hPZWxKTWhJZ2Vp
            VVRBNGtrcFkrUFJRWEQyekhjQnduY2cKry+2oaSQGCV4WJ9Ztih/ueLuxRyT++ft
            x7TZo1XNj01LdZqxRfIzpndak5gL5V0xYSFfHCL8KE4ynyuYHX3eCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T06:05:31Z"
    mac: ENC[AES256_GCM,data:GH7IakeaNsjxQ7FdlAQAZxrHKxpfU6JwhNwV/ISynHGFrAmigO45Zu7glNcVXZInnWHvSfmSHX+VpOBC7EpWKPvNejERCvvSbI1uSZPH5W7GcR15fNTN3r1tY02h8z7KuIJmJGm8xsZlAnw9z7F92JMBHe7eeRrzHtMXP14EGI8=,iv:DBBuUYK3NJ0ZXwiG74JBn4ZWlU0AQeK32ibzrazhqoI=,tag:kCungo8MPNSK1QdppalHbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
