apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:s4W7MXBIbf8ugBebI5PE/ruQnUT3n5h9gsU+kWr9qnzjrzlz,iv:QweeTg5t+MquLqarvDxs1IAN3gd44DXM5/bpguqaqyA=,tag:ag1ndsNdJqsuropA+J406g==,type:str]
    credentials.json: ENC[AES256_GCM,data:Orpv6p7F3Etl+woc/eucmw1wPyx75ap+uyyydlqsy9CRYO6qVLdfAP9i7Y2xPaJDa1bF1MpWk1rrJGs7MwvTAz62oPugOBWqQGr7U4iQSABrqwso2GzGOyqu608FfoupXmmHCj1s9W6qmXoIi5wznMlrdCBlJFoAGLzTj4EVb6L3DdqQLNLyqrQ2bxqeUROQOKqwXHbtdGKfCDejp0vzx3aNXsaMJJ60TkQ6oh8law==,iv:ivTYxK4bBshjCtlbmnEkGtlL3he8VIFh0GrAIITdIV4=,tag:YUP3AC0AzuLCP0v+a6C/ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUkRGN3FjNitNbFN1bld5
            Wkp2WjlkdHVOMk5BbDIySEExUEdiTW03dVhnCms5b3dSUHFSTGI5ZUdHVnNQT0VL
            N05ENkxGQkNlMnFuWDhtdHNoUmF6RjgKLS0tIDVEOVdsUkwvcTdKbElpekZNUGxp
            ZGsyN29lbWZZRnJLNTZmVXRpdmtYTXMKgH4ElxyXiCrjmdslkuDo8LGxwhu/6gXu
            lD1lmJ6YvixE1giHNXTzSGov80cqoQDRveDi1iUjN02Cphe6HNIFog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T05:51:54Z"
    mac: ENC[AES256_GCM,data:sOe2lK6QrZ/+941ludqM9y4nLSP6aRFoZbRt2cmXYtiG0/Rk6zAljrTdTefhCzyKRO/55hECn3Em9qEDQx+y6ePUKeF61ze8SArRgaB4QJ654CSMCrVj0JMmrWDNDMJloYmlPZUwJ/1kdSKp/lH6VbKOTv2BBwudLw4FWNWeBkU=,iv:2h26qRn4LU3bo6pOYRzbaa8VTULCynJlEM/6Xrz1Rm0=,tag:aoyPCO1POTYiNknwdhDxmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
