apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wDSxO6qixrHOlIYECUb8cu1EKw06HnNaSsgZAAyR5CTEm0Qg,iv:TJKAGdv1c8ZEmiJSfSk/CINAlj2p9YiPEaZTfJzQmAU=,tag:NZSxB9Ry5GXKhlYDopYVug==,type:str]
    credentials.json: ENC[AES256_GCM,data:q7WBr6LBeRfg1IJ0+1kMpubTrAZZUJD4fA9D8d+AD1fLlVBABSro3FSXlxJV68bNgsEQ9qp5RwZPgWHzNUnZF2ydEq94Xos10JqpSZWXpsOTtkzgpPzXiywFzJOIRfhkp6fDJrhVwoCYb4HeGV2TAIis1Bmw1suGx8u/UbM9OXaDvBn1d8Bj9bFW8+fygiw09J6f9iV1SuNWXeF64gvUcd5rmJyIeCYGqAdCA65NaQ==,iv:rPoIf8mqabr8/mKUijSvQFfGjfvXqp5reZjQM0w2Ax4=,tag:tvUyxspb9DwokVEcM+5zEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYWlUSFJZQjlJZHFqRHZs
            RnJZYTZRZ3pVRmpiTXF6c3NmSi9pUGFtNUZNClVob2NBVUZiYVYyTHdEaWFwNDdl
            d2JwcDF1eS83Mk40d3hVd2JVOVdiaU0KLS0tIDdDT3ZHNVpnS2lUM2JjdDVNZWNT
            MlZzS05KZjJWcVZDWTRaMUt3aHNHQW8K//qkwN8E/Xxwf7nBz7S1tYDUVyzMWY1x
            GHu1ynbtYBytM5LHEdZErt76sczF5qRx8IGKH7grtoRNkj2GVwQRnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T00:50:09Z"
    mac: ENC[AES256_GCM,data:3w8osJf7qj8iZ/4bBWO9BQx1JLMOuWckgDwplTWRAZ6nAPSNqOwyz+XbLCG/QLALODpg6Rmj3YJVEp88h0lXYAOtdKxV5PqI4IG0geCV61eFSbpe8xbrtEZv9aCWPO/HbkEGBUKxP0sVsAlcEWK2NfJLIZesgmYq6EIuSNvwoR4=,iv:ai1kHSmcqYNHaalMGgzhwXDprHIzpGMK/YZuXk2NdkI=,tag:pBtE6i53aptuw6mrkmMBow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
