# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:6KTw8ACNclJLlrsYAP/XkcOzJMUy5CzL0hsI6qBCi5H0t3KU+pZU4Q==,iv:lVRdrYHR1cNSpEYVdU+e/6mhfKZv3WpmdfmbU0XOr7s=,tag:2SQ876LgY614QLtzyMF6tg==,type:str]
sops:
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQzVrc1ltd1E4MWZpd045
        ckxuSHZrMUpmdXptVFpRSFhKcmxyVDRxb0Y4Ck1pTWxEdS9ia3BJVUorb2xQcXlo
        aHYyNzNOclNMSW1uNEI3N1R6R2xNT1kKLS0tIEN2azF6cFN3aEZaYUd4QkEveURI
        UXVPM1VpNm9YQUcvNXNtaEdjSmdBQkkK02Pn05DJEUe18ux37vXC6Z4mQzA1LZJr
        kkgfs9aIuNdIvCPSMGdzjExQ0bkwI15ONMyPpcpHUmvpdCGq9ynA2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-22T00:55:03Z"
  mac: ENC[AES256_GCM,data:iow7Kgr5N4a3H+RUl6zt39X6x8lTaSQ5m16RXj3so6BcoHuobTLTu0hMnnjUuZ1XOcRJp4bfK6w5ngMH5eTdceHKXILIw/NwbWD1LP6if/zGRh/KAstJBmkF81aQSRpBqHPxgBG0vlWIZkJg4BcY18W0mVrOmq+bHrL8oUlVK18=,iv:AlVX7O23R1aQ5elJZpLjAIIlvCGU3G60ftE03ZjnvPQ=,tag:EoP4/9AinLZ1cMRLKC82Gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
