---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-external-secret
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # open-webui
        OPENAI_API_KEY: "{{ .OPENWEBUI_OPENAI_API_KEY }}"
        OAUTH_CLIENT_ID: "{{ .OPENWEBUI_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPENWEBUI_OAUTH_CLIENT_SECRET }}"
        WEBUI_SECRET_KEY: "{{ .OPENWEBUI_WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: openwebui-external-secret
