---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # pgadmin
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_PASS }}"
  dataFrom:
    - extract:
        key: pgadmin-external-secret
