---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-oidc-config
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        config_local.py: |-
          AUTHENTICATION_SOURCES = ['oauth2', 'internal']
          OAUTH2_AUTO_CREATE_USER = True
          OAUTH2_CONFIG = [{
              'OAUTH2_NAME' : 'authentik',
              'OAUTH2_DISPLAY_NAME' : 'Authentik',
              'OAUTH2_CLIENT_ID' : '{{ .PGADMIN_OIDC_CLIENT_ID }}',
              'OAUTH2_CLIENT_SECRET' : '{{ .PGADMIN_OIDC_CLIENT_SECRET }}',
              'OAUTH2_TOKEN_URL' : 'https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/token/',
              'OAUTH2_AUTHORIZATION_URL' : 'https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/authorize/',
              'OAUTH2_API_BASE_URL' : 'https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/',
              'OAUTH2_USERINFO_ENDPOINT' : 'https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/userinfo/',
              'OAUTH2_SERVER_METADATA_URL' : 'https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/pgadmin/.well-known/openid-configuration',
              'OAUTH2_SCOPE' : 'openid email profile',
              'OAUTH2_ICON' : 'fa-lock',
              'OAUTH2_BUTTON_COLOR' : '#0064a5'
          }]
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: pgadmin-external-secret
