# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:h7z+EjNW8++hJNfMRmVTX8gMTf6HA2bf+0Ak5zsp8AI=,iv:DeR5vPtj5DxBebivk9LOfQQXJAp5p59t0Z9uljG8mlM=,tag:NfYYoHSpX9yp/lQDH7qjFw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y3JIQjIrTlhPUG4xUUpX
        NTlLK2VPS1RTTldDM2p3R0xVdnNKU2RiTFc0CjFWWU9HWkE1Q3MxSG1xWGxqZi94
        RmhyWERZR3dZdXQwQ1dxMFFXYTNBaGMKLS0tIHYwVGx5S21pMEY2a3d1ZHJma29t
        K2ZGc1NoNU41NDJNUzl0cnZMYXMwaWsKmBdTHylyZ9zKrmhPweuzfowdv4lFX25p
        u3j7L/smWLwr4HADHERATzcyZ7WkOmyLjf1CD3ZTLT45SFoN+g0naw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T05:35:58Z"
  mac: ENC[AES256_GCM,data:SrNuSTaGELUtfO8lMdd6V+CWHJKoIu/SK5bo+q6UfWUQVSqN+UIdHdQEymBclQ2iHoWlo0isngPnCHgz1hU1gWKiD5LZZ07a/hf5Nh1R5/JXOQwaZy3EGVQVH4zm0NswoXQWDo0Zo2op6NpfAkoPRggnvfZCuQqoO4zPpVpleWA=,iv:03htE3OPmr+Y2hmHThxn7TXxPTdUZP/cE4+tHTdEFac=,tag:Kta0zP/yrHvBurq3oN4xgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
