---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
  namespace: utilities
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      paperless:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret paperless-external-secret
        initContainers:
          01-initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
            envFrom:
              - secretRef:
                  name: *secret
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.11.4
            env:
              PAPERLESS_TIME_ZONE: "${TIMEZONE}"
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
              USERMAP_UID: "1026"
              USERMAP_GID: "100"
              # PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: "HTTP_X_AUTHENTIK_USERNAME"
              PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_CONSUMER_POLLING: "120"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMPTION_DIR: "/data/nfs/consume"
              PAPERLESS_DATA_DIR: "/library/data"
              PAPERLESS_MEDIA_ROOT: "/library/media"
              PAPERLESS_EXPORT_DIR: "/data/nfs/export"
              PAPERLESS_OCR_LANGUAGES: "eng hin guj kan"
              PAPERLESS_OCR_LANGUAGE: "eng"
              PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created_month}/{title}"
              PAPERLESS_TIKA_ENABLED: "true"
              PAPERLESS_TIKA_ENDPOINT: "http://localhost:9998"
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://localhost:3000"
            envFrom:
              - secretRef:
                  name: paperless-external-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
          gotenburg:
            image:
              repository: thecodingmachine/gotenberg
              tag: 8.9.0
            env:
              DISABLE_GOOGLE_CHROME: "1"
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-full
    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      library:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 5Gi
        advancedMounts:
          paperless:
            app:
              - path: /library
                readOnly: false
      nfs-data:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 5Gi
        advancedMounts:
          paperless:
            app:
              - path: /data/nfs
                readOnly: false
