---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # paperless
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD:  "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_REDIS: "redis://:{{ .REDIS_PASSWORD }}@{{ .REDIS_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_PAPERLESS_DB }}"
        PAPERLESS_DBENGINE: "postgresql"
        PAPERLESS_DBHOST: &dbhost "{{ .POSTGRESQL_HOST }}"
        PAPERLESS_DBPORT: "{{ .POSTGRESQL_PORT }}"
        PAPERLESS_DBNAME: &dbname "{{ .PAPERLESS_POSTGRESQL_DBNAME }}"
        PAPERLESS_DBUSER: &dbuser "{{ .PAPERLESS_POSTGRESQL_USER }}"
        PAPERLESS_DBPASS: &dbpass "{{ .PAPERLESS_POSTGRESQL_PASS }}"
        PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
        # PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "false"
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .PAPERLESS_OIDC_CLIENT_ID }}",
                  "secret": "{{ .PAPERLESS_OIDC_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ]
            }
          }
        # postgres init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: paperless-external-secret
