---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./postgresql/ks.yaml
  - ./pgadmin/ks.yaml
  - ./mosquitto/ks.yaml
  - ./redis/ks.yaml
  # - ./nocodb/ks.yaml
  # - ./baserow/ks.yaml
  # - ./cloudnative-pg/ks.yaml
