---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudnative-pg/ks.yaml
  - ./pgadmin/ks.yaml
  - ./mosquitto/ks.yaml
  - ./redis/ks.yaml
  - ./grist/ks.yaml
  # - ./nocodb/ks.yaml
  # - ./baserow/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: databases
    target:
      kind: Namespace

