---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./weave-gitops/ks.yaml

