---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-nfs
spec:
  storageClassName: calibre-nfs
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.90.250
    path: /volume1/homelab/calibre
  mountOptions: ["nfsvers=4.1", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-nfs
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: calibre-nfs
  resources:
    requests:
      storage: 20Gi
