---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
    - name: onepassword-connect
      namespace: security
  values:
    annotations:
      secret.reloader.stakater.com/reload: &secret calibre-external-secret
    controllers:
      calibre:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V2.0.1
            env:
              TZ: "${TIMEZONE}"
              PUID: 1026
              PGID: 100
              DOCKER_MODS: "linuxserver/mods:universal-calibre"
            envFrom:
              - secretRef:
                  name: *secret
    service:
      app:
        controller: calibre
        ports:
          http:
            port: 8083
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            https://calibre.${SECRET_DOMAIN}/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://calibre.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: calibre-nfs
        globalMounts:
          - path: /config
            subPath: ./config/
            readOnly: false
      cwa-book-ingest:
        enabled: true
        existingClaim: calibre-nfs
        globalMounts:
          - path: /cwa-book-ingest
            subPath: ./cwa-book-ingest/
            readOnly: false
      library:
        enabled: true
        existingClaim: calibre-nfs
        globalMounts:
          - path: /calibre-library
            subPath: ./library/
            readOnly: false
      books:
        enabled: true
        existingClaim: calibre-nfs
        globalMounts:
          - path: /books
            subPath: ./books/
            readOnly: false
