---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2024.10.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: onepassword-connect
      namespace: security
    - name: cloudnative-pg
      namespace: databases
    - name: redis
      namespace: databases
  values:
    controller:
      annotations:
        secret.reloader.stakater.com/reload: &secret authentik-external-secret
    worker:
      replicas: 1
      envFrom:
        - secretRef:
            name: *secret
    server:
      replicas: 1
      initContainers:
        - name: 01-init-db
          image: ghcr.io/onedr0p/postgres-init:16.3
          envFrom:
            - secretRef:
                name: *secret
      envFrom:
        - secretRef:
            name: *secret
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - &host "auth.${SECRET_DOMAIN}"
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: *host
            hosts:
              - *host
    authentik:
      email:
        host: "smtp.gmail.com"
        use_tls: true
        port: "587"
        from: "Authentik <authentik@${SECRET_DOMAIN}>"
      log_level: info
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      error_reporting:
        enabled: false
    prometheus:
      rules:
        enabled: true
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
