apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2+QkPxaYqKgNuRs8I96vfUy6QyFIKLor6yleCgA0iT1vXuKS+OM8KA==,iv:ZECaBG3qR1KKNtfpgBHzBTpAMLlxb1xgkuTXv1UWtak=,tag:n1iwXi3dIUCOAtvxgUXVkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQTRibVFMU1hFRmZqRXFH
            ZUJpMlVmVDJrWDlXRFAwZDZlZWtQaU1yWWlBCmpYODdpZ0VFeS9pOFphaWFrZmZM
            MnlCRk0vT2VvRWN4V0YrbXE5WlBBSlkKLS0tIExCcG0wTGFDQW5ET0h0ZGd6QmZv
            UkJVR0ZNZTZ3dm1IYXY0WTFIMWh2UXMKOlSoIFaB496VFgc4szbU4ioweDj1BZPi
            ts4wTo0+59O6UQ3ivSHEYyzC0aC11xM58TdOCf6amsAYV81+0xPW8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T23:18:34Z"
    mac: ENC[AES256_GCM,data:97nkC78wTqoi9n38aM2ZX02meOAPJwZuaYy+q6nqsRBL0gzPmEom7sa4eAqOKFF+SNTABOaQgUENM4PSTlAbcg7TVkKLyWeHd8RQaVCJ+vF4YfT+EUM9HSKBQOK0wnV3LV8ujFttj+lxHhOq86MnXFNaHCXl+OdJ4MgHQokYHtY=,iv:xpGDbGEvjj2uPZ4U7o6ufIW+Rmo2838YBgua9Oc9RtU=,tag:0avWpHUHRxL7/QmCLvvIYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
