apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:m030ISVhtc8PV2OHreI4/ccb9En2KDEo7tBHsuywhEhKRmIu8JFrEA==,iv:znGSHfwg2bafIGdsX9Gs7AFxFYb08hJb7GgiqITAcMc=,tag:X0umh3zlwoor/YfJG0k+MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS1dHN2Y2VUFGUDNyQVk0
            d0xPR3FZOFpkQnBUeWkvN2FCS0F2V3hiQkE4CkVhbE94QklUY2IrdEJzWDRianZl
            WGZhcGE1SlcrZ1JCNW5xSGdOZGJJYU0KLS0tIHhZS09DTTJsdVIvVlloYmtwSHB1
            MHdtakJ4SHVIdVFVNVd0OWNvZjFGMHMK0cM2bXPNbE/8batRvn0vuQ75rPMLcVuD
            5Hk1dhs3xKRRNf2MutrYId6VXMoQt+m7M3r/BIg3CHGPLngqqTSB0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T05:52:11Z"
    mac: ENC[AES256_GCM,data:X9NTAdhufe4e2UxbnmoyDdTAy2FI8RN5cL42aCjX0XLIEoc4t2HYpUzq85tU35AqhVT/N6qzvpkI5Xi1z8wMEP7oxcq6GpW7eKjjrVeKaV7VmhEnzjF8FFWMhx9oFN3PfJP6Ivqm1oqFS2sctCytw3eOHGc7h7TRBtENtlU3ae8=,iv:Ydsbe4GIGHH6/+pkSSKogc/qRfrOmdP2B4Sh+3YuZVU=,tag:3WVPnkqjvepHPqkYWw014A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
