apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:mQYO0wLQgStXnGmEY8SZ3VaZvX0gZTAVorW9IVKTAg5Y8eDDfaRuVA==,iv:uU12KvMpIwCVefYCgUTQbdj493ESDTs454y3pasiEAo=,tag:AxJ2mtauO+ZWWCL55TsqZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU2VjN1FuWFllZGxrMy9C
            WlVPSkdicmZzZUZSVktuWFJKbXJMQjF3MGdzCjJ2Sm1wNzh1aGZiTE03eDEzbWNi
            dHRvMGtCZmVjbkNsREErdEtFdlY0cXcKLS0tIGdYTmk5WSt3ZVJhMTBqU25oQ0pw
            RGN2UGNzYVYzV0JLcC9QVnhiK09mczQKnIkYegpF7idaLNUlJWt/VOEG/s0/wqUR
            QRM1wt9GOGxHEG+c7w1jrIOE8J9gL8t02d5av5oq1+5i1YUKssH+sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:24:33Z"
    mac: ENC[AES256_GCM,data:9FthmpF0kBrFRHpDikm8Mf4pLjfpShJpPUtOWx8PzA1RvauYPIumCu3NAJ78g3q+Nyxuq3+6LuDstTTGt9tr8z1adBzZdtyhhk6VfUp8vyWLzyfSaEnlZqxVU7R0KREXDX18W1DBAKxXJY3xyQdHpWeVbJoq4UL+tNmKaWN8l8Q=,iv:VgE8J3oMyT+EnOCvdPFTjE+CxaQKSpf9rfLrLKdJl0o=,tag:3pfUB8nZFMtD0do5PtoOvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
