---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-external-secret
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # n8n
        N8N_LICENSE_ACTIVATION_KEY: "{{ .N8N_LICENSE_ACTIVATION_KEY }}"
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        N8N_USER_MANAGEMENT_JWT_SECRET: "{{ .N8N_USER_MANAGEMENT_JWT_SECRET }}"
        N8N_EDITOR_BASE_URL: "https://n8n.${SECRET_DOMAIN}/"
        # N8N_HOST: "{{ .N8N_HOST }}"
        WEBHOOK_URL: "https://n8n.${SECRET_DOMAIN}/"
        DB_TYPE: "postgresdb"
        DB_POSTGRESDB_HOST: &dbhost "{{ .POSTGRESQL_HOST }}"
        DB_POSTGRESDB_PORT: "{{ .POSTGRESQL_PORT }}"
        DB_POSTGRESDB_DATABASE: &dbname "{{ .N8N_DB_POSTGRESDB_DATABASE }}"
        DB_POSTGRESDB_USER: &dbuser "{{ .N8N_DB_POSTGRESDB_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbpass "{{ .N8N_DB_POSTGRESDB_PASSWORD }}"
        N8N_EMAIL_MODE: "smtp"
        N8N_SMTP_SSL: "true"
        N8N_SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        N8N_SMTP_PORT: "{{ .HOMELAB_SMTP_SSL_PORT }}"
        N8N_SMTP_USER: "{{ .HOMELAB_SMTP_USERNAME }}"
        N8N_SMTP_PASS: "{{ .HOMELAB_SMTP_PASS }}"
        N8N_SMTP_SENDER: "N8N <{{ .HOMELAB_SMTP_USERNAME }}>"
        # postgres init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: n8n-external-secret
