---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # immich
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        DB_DATABASE_NAME: &dbname "{{ .IMMICH_POSTGRESQL_DB }}"
        DB_HOSTNAME: &dbhost "{{ .IMMICH_CNPG_DB_HOST }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_POSTGRESQL_PASS }}"
        DB_USERNAME: &dbuser "{{ .IMMICH_POSTGRESQL_USER }}"
        DB_PORT: "{{ .POSTGRESQL_PORT }}"
        DISABLE_REVERSE_GEOCODING: "true"
        ENABLE_MAPBOX: "false"
        LOG_LEVEL: "log"
        NODE_ENV: "production"
        REDIS_HOSTNAME: "{{ .REDIS_HOST }}"
        REDIS_PORT: "{{ .REDIS_PORT }}"
        REDIS_DBINDEX: "{{ .REDIS_IMMICH_DB }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        # TYPESENSE_API_KEY: "{{ .IMMICH_TYPESENSE_API_KEY }}"
        # TYPESENSE_HOST: "{{ .IMMICH_TYPESENSE_HOST }}"
        # TYPESENSE_PORT: "8108"
        # TYPESENSE_PROTOCOL: "http"
        # TYPESENSE_DATA_DIR: "/config"
        IMMICH_WEB_URL: "http://{{ .IMMICH_WEB_HOST }}:3000"
        IMMICH_SERVER_URL: "http://{{ .IMMICH_SERVER_HOST }}:3001"
        IMMICH_MACHINE_LEARNING_URL: "http://{{ .IMMICH_MACHINE_LEARNING_HOST }}:3003"
        MACHINE_LEARNING_CACHE_FOLDER: "/cache"
        TRANSFORMERS_CACHE: "/usr/src/app/.transformers_cache"
        IMMICH_API_URL_EXTERNAL: "/api"
        # postgres init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
        # immich-db cloudnative-pg
        username: *dbuser
        password: *dbpass
        POSTGRES_SUPER_USER: "{{ .POSTGRESQL_SUPERUSER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: immich-external-secret
