---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # immich
        # JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        DB_DATABASE_NAME: &dbname "{{ .IMMICH_POSTGRESQL_DB }}"
        DB_HOSTNAME: &dbhost "{{ .IMMICH_CNPG_DB_HOST }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_POSTGRESQL_PASS }}"
        DB_USERNAME: &dbuser "{{ .IMMICH_POSTGRESQL_USER }}"
        DB_PORT: "{{ .POSTGRESQL_PORT }}"
        DB_VECTOR_EXTENSION: "vectorchord"
        IMMICH_LOG_LEVEL: "log"
        IMMICH_ENV: "production"
        IMMICH_TELEMETRY_INCLUDE: "all"
        REDIS_HOSTNAME: "{{ .REDIS_HOST }}"
        REDIS_PORT: "{{ .REDIS_PORT }}"
        REDIS_DBINDEX: "{{ .REDIS_IMMICH_DB }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        MACHINE_LEARNING_CACHE_FOLDER: "/cache"
        # postgres init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
        # immich-db cloudnative-pg
        username: *dbuser
        password: *dbpass
        POSTGRES_SUPER_USER: "{{ .POSTGRESQL_SUPERUSER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: immich-external-secret
