---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kavita-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # kavita
        # PASSWORD: "{{ .KAVITA_PASSWORD }}"
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: kavita-external-secret
