---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # coder
        CODER_PG_CONNECTION_URL: "postgresql://{{ .CODER_POSTGRESQL_USER }}:{{ .CODER_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST_INTERNAL }}:{{ .POSTGRESQL_PORT }}/{{ .CODER_POSTGRESQL_DBNAME }}?sslmode=disable"
        CODER_OIDC_ISSUER_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/coder/"
        # CODER_OIDC_EMAIL_DOMAIN: ""
        CODER_OIDC_CLIENT_ID: "{{ .CODER_OIDC_CLIENT_ID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OIDC_CLIENT_SECRET }}"
        CODER_OIDC_EMAIL_FIELD: "email"
        CODER_OIDC_SIGN_IN_TEXT: "Authentik"
        CODER_OIDC_SCOPES: "openid,profile,email,groups"
        CODER_OIDC_GROUP_FIELD: "groups"
        # CODER_OIDC_GROUP_AUTO_CREATE: "true"
        # CODER_OIDC_GROUP_MAPPING: "{'homelab_users': '', 'homelab_admins': ''}"
        CODER_DISABLE_PASSWORD_AUTH: "true"
        CODER_OIDC_ALLOW_SIGNUPS: "true"
        CODER_SECURE_AUTH_COOKIE: "true"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .CODER_POSTGRESQL_DBNAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .CODER_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .CODER_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: coder-external-secret
