apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:w0Heh/k=,iv:3V6JPNdBgOTMVtd9NhCxNlNQQM4I6JdyAcLRhHSANJ0=,tag:m23NT0ZaS18IMMHzTGP18A==,type:str]
    password: ENC[AES256_GCM,data:aZPDtiMHoEH4r/sHbMC6L5Jxj3h2/CPxNzGaKCMmKlfjE0NF2jlO5k1CGA6ry61IqbEQ60XCn/3veUiT,iv:5iMTELOQ57slY7tgGoJzseKYlRLs8RcB6Kut4oHanmI=,tag:coddEFZYIxEURZTomURjew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1unasehwk8uqa043j8cugh96hx8299s9t4x3y4nqkufs9779ahexsf72lr0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERXMyMTRMdDd4Rk8wVTlI
            YlkwakRiR0tmcU1YZENVd2FzVGxSdmYrNkJrCmZBUDRuTWJXOUovRkU5bmFPWi9T
            R3o1cmdOTHdmQW9CdDUxbGprTVlHMHcKLS0tIFJGUDFleWNtekNFZmZPd21sNEV1
            N2gvZWdBVDQ5bGQrR1lsMGR2T2dRREEKP4rjDHP6ljPj+qN0+awj3CpU+ahCkdZG
            26wwlmS1NG3ov0Gl8U7LMPTkebPbZ9WODAGJvBcdOapGnIsFHNcmew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T16:58:23Z"
    mac: ENC[AES256_GCM,data:d6yb8SFc77Ne0e9TwwdbCXNYtSjH8W8XGo+5F0zvlwDYFoEeT44sjVQl3jm0RclVYfxOLkFPfkaow18dupo+Q4O58Q9OsMVp7+zep6X5pxe09az2b5awtZ/cEgxeq9Ia3F2rQYs3KpSSwhd8OZu3HUva0Q0w5ajcZgpp1nt1S2c=,iv:NyVeTH0EveM+Ea8/XrX1VDCUScMtl70wJ4tu3kOC7iM=,tag:a3OSTDIxus75FNERNqy3SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
