---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  ## User repos
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./cloudnative-pg.yaml
  - ./coder-v2.yaml
  - ./csi-driver-nfs.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./kubernetes-dashboard.yaml
  - ./open-webui.yaml
  - ./piraeus.yaml
  - ./weave-gitops.yaml
  - ./xenitab.yaml
  - ./windmill.yaml
