---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: storage
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externalSnapshotter:
      enabled: false
