---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grist-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # grist
        GRIST_SESSION_SECRET: "{{ .GRIST_SESSION_SECRET }}"
        GRIST_TELEMETRY_LEVEL: "off"
        GRIST_FORCE_LOGIN: "true"
        # GRIST_SINGLE_ORG: "homelab"
        GRIST_DOMAIN: "{{ .HOMELAB_SECRET_DOMAIN }}"
        # GRIST_DEFAULT_EMAIL: "{{ .HOMELAB_ADMIN_EMAIL }}"
        GRIST_OIDC_IDP_ISSUER: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/grist/"
        GRIST_OIDC_IDP_CLIENT_ID: "{{ .GRIST_OIDC_IDP_CLIENT_ID }}"
        GRIST_OIDC_IDP_CLIENT_SECRET: "{{ .GRIST_OIDC_IDP_CLIENT_SECRET }}"
        GRIST_OIDC_IDP_SCOPES: "openid email profile"
        GRIST_OIDC_SP_PROFILE_NAME_ATTR: "name"
        TYPEORM_DATABASE: &dbname "{{ .GRIST_POSTGRESQL_DB }}"
        TYPEORM_HOST: &dbhost "{{ .POSTGRESQL_HOST }}"
        TYPEORM_USERNAME: &dbuser "{{ .GRIST_POSTGRESQL_USER }}"
        TYPEORM_PASSWORD: &dbpass "{{ .GRIST_POSTGRESQL_PASS }}"
        TYPEORM_PORT: "{{ .POSTGRESQL_PORT }}"
        TYPEORM_TYPE: "postgres"
        # postgres init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: grist-external-secret
