---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vikunja-external-secret.yaml
  - ./vikunja-caddy-config.yaml
  - ./vikunja-external-config.yaml
  - ./helmrelease.yaml
