---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # vikunja
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_SERVICE_JWTSECRET }}"
        VIKUNJA_DATABASE_TYPE: postgres
        VIKUNJA_DATABASE_SSLMODE: require
        VIKUNJA_DATABASE_HOST: &dbhost "{{ .POSTGRESQL_HOST_INTERNAL }}"
        VIKUNJA_DATABASE_DATABASE: &dbname "{{ .VIKUNJA_POSTGRESQL_DBNAME }}"
        VIKUNJA_DATABASE_USER: &dbuser "{{ .VIKUNJA_POSTGRESQL_USER }}"
        VIKUNJA_DATABASE_PASSWORD: &dbpass "{{ .VIKUNJA_POSTGRESQL_PASS }}"
        VIKUNJA_MAILER_ENABLED: "true"
        VIKUNJA_MAILER_FORCESSL: "true"
        VIKUNJA_MAILER_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        VIKUNJA_MAILER_PORT: "{{ .HOMELAB_SMTP_PORT }}"
        VIKUNJA_MAILER_USERNAME: "{{ .HOMELAB_SMTP_USERNAME }}"
        VIKUNJA_MAILER_PASSWORD: "{{ .HOMELAB_SMTP_PASS }}"
        # postgres init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: vikunja-external-secret
