apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4gADqHXDufwp,iv:W148std5DKVd+ta2DhP1IDNeOjxE4xdMuQBCO0t16Fo=,tag:5fSV/RA2VYZaK4csYqZQKw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EA4N4uiye6uV+J7GcMSLdtMfBvWbFcBRFd5vD3AUdaZI45+y,iv:2DTWDMZbtMsHzCqWNNyXeg2l6SVWzKbCA/cnNNzacEg=,tag:/vuinNkPV4Wmbrg2eHqw1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa0FKR0JmdWcyK1FINEN0
        NG1pQ1VWeTYvMEFLVTlnS1VoSXJGVTBhcm4wCjJUQ28xYk1DaVk2bHd2OEhUaXBi
        eTJpRHNZbTc5UHh2QmJvK1dCUTkrZDgKLS0tICszak1LeU9ZWk9QaUZmY014bFNH
        bkhJL0xIVUJoRFo3SWRqM2lHZU95ODQKqKVhd+O+VLR3Zfo7vZqS+PKgojdHO4fy
        KGrpxma5q+AoktUxV8mNk1fFI+vTWHE43aV0XP8q+CuS4Neuw+mNHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-23T00:45:48Z"
  mac: ENC[AES256_GCM,data:TPTMpuz4UjpKminAgKp2E9l1sOJat52FwfNAwqffX5SuL9dRkVA2oSxVM0Fr6Jth1hqRIViuaFN9KwGMoMTTS7qb6CkHFjWhWsPo27zRZGIHyRvJB7u/WHxsOTx3gPpFuFzIqUSsM8mOQ9I9H3TJaTa9qGGes00snYU3fST3mow=,iv:VIFmw1VyeoX15KoJJkYY/NPNREJbyTtSmxj0YWabaUM=,tag:G/QU0PEsbTDwCAlGV0JSgQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
