apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:2ge18tQOUge//wIv118zg2JozaaZsmN0NMtlMPw/RqASIh/0jCPa0nfxCztbB5NeRpy/MhNKh3X2reXaSl2zBqjuNjloEQGzoJc=,iv:0PhsQo9PXRZhuasCaIKg5viwGHOj2nobqZHCOlyLgLs=,tag:LWbewiwbFDwpC1P7pKJ0Ug==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscjhabFZ6NDZiWHRZQUpR
        UDJ6N1BhVWNYOExZaVRITWd6RmhDTldrRUhzCmZOTCszUEpJZnlnZ05FWitXN2RN
        VG1tM09wdi9VbHRIajN3SnN0MXFrS2sKLS0tIHFFaXNFNm44Q3FMWFNMVXNaOXgv
        cDdzWXlCQUpPMytHRDcwSm5Galg4QlEKqBSTLD5MRmELujNuDuCWQvblTmG3KQFy
        ajQ6Np4Wq5Yfr5WDwzkt2aLD5DabdkVNwiGxt7htCpkRWzOzo+CzEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T18:22:07Z"
  mac: ENC[AES256_GCM,data:znlB+MS+ao915e+/5iB/i/ORoKFFzwvxZV3ADBlSx2RRuyfGFUZG9pP8riK9TIA2oj43P+Syrqdeyv3z/K5IegSpPevNep6DnTcElAR6HscLSvFII8VoQPNz1qzFY1DDx8ZM/FKjvFijhKz9FVwic+QeLu3nCq+m8rUBgzun5yY=,iv:fSgO2iVve0cgB4Q84sAjPzWUXcqijX+j/ShyzdEFRvc=,tag:wkkepKGXFYWSWrbnv0OWLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
