# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:N0tZ0zT/JUcAmGJmMjX6tg3SsrQkLhkOsxULjwQwUE0IpVwggtmuCA==,iv:Lh15iglIX6rxFy477CFdVbsDrJnho921m1OpBBPjDY4=,tag:B4qXAJ2htrETdhtGFQgtKQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST2pQV3V3SitNQVkzKzNx
        RDZtTzg4MysyWE1ueUpjQnN5d01mN2hob0VVClpkdjhmcitPRFFoVW5NNFY2MTYw
        cjRYVER6am9zVHVscis1ZmtnTVRFYmsKLS0tIC9obFQ5WXp4dGtuSGFxYXl6clNv
        TmlRSnNMZjNnZndWeDlIVkFOYUpyNGcKjfXWUjqnTYS6wHdFisqJX3mvrd55HnGi
        5Vr3xDA36VtsahWGs3kK6kpCAuiJGxFZvtZ7Dl9So91h5NQVsrJF0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T18:22:07Z"
  mac: ENC[AES256_GCM,data:PfwkykcjorWA+dPr0N80dXvSUA68kvVt5i97vOjuGMYxJ31TiYOMwontbLGomQHeJiKuWueg3NYUwRvp94b5kUVmuNoMyIRHMVyEo9NKVu4SarxZD4STqKGB8h1B44t1OP6yB8KOVzRpfJZfOjXY+GAcCCJP2oROGIsSz0Nysks=,iv:76HjaIVLVNpuYcbd0UMj4xl6+49ppa2HwxC2MKvREAA=,tag:BECXg2qsSFN2U60oF/dEaQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
