---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: appflowy-db
  namespace: databases
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 20Gi
    storageClass: nfs-csi
  superuserSecret:
    name: postgresql-superuser-secret
  postgresql:
    parameters:
      timezone: "America/Los_Angeles"
    shared_preload_libraries:
      - "vectors.so"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    # ########################################################################################################
    # Minio bucket configuration for current backups. serverName corresponds to a folder name in the bucket.
    # Note: Change *currBucketFolder at every new recovery bootstrap.
    # ########################################################################################################
    barmanObjectStore:
      wal:
        compression: &compr bzip2
        maxParallel: 4
      destinationPath: &dest s3://appflowy-db/
      endpointURL: &minio http://minio.storage:9000
      serverName: &currBucketFolder appflowy-db-1
      s3Credentials: &s3creds
        accessKeyId:
          name: appflowy-db-external-secret
          key: aws-access-key-id
        secretAccessKey:
          name: appflowy-db-external-secret
          key: aws-secret-access-key

  # ##########################################################################################################
  # Bootstrap a brand new cluster with a new app database and owner.
  # ##########################################################################################################
  bootstrap:
    initdb:
      database: appflowy
      owner: appflowy
      secret:
        name: appflowy-db-external-secret

  ##########################################################################################################
  # Bootstrap a new cluster from a backup in the *prevBucketFolder folder in the bucket.
  ##########################################################################################################
  # bootstrap:
  #   # Use this to recover a net-new cluster from a backup
  #   recovery:
  #     source: &prevBucketFolder appflowy-db-1
  # #     # recoveryTarget:
  # #       # Time base target for the recovery
  # #       # targetTime: "2024-02-26 00:00:00.00000"
  # externalClusters:
  #   # This represents the s3 backup to restore from, the backup must be the same major version of the target cluster
  #   - name: *prevBucketFolder
  #     barmanObjectStore:
  #       wal:
  #         compression: *compr
  #         maxParallel: 4
  #       serverName: *prevBucketFolder
  #       destinationPath: *dest
  #       endpointURL: *minio
  #       s3Credentials: *s3creds
