---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-external-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
  data:
    - secretKey: username
      remoteRef:
        key: immich-external-secret
        property: IMMICH_POSTGRESQL_USER
    - secretKey: password
      remoteRef:
        key: immich-external-secret
        property: IMMICH_POSTGRESQL_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: immich-external-secret
        property: IMMICH_MINIO_ACCESS_KEY
    - secretKey: aws-secret-access-key
      remoteRef:
        key: immich-external-secret
        property: IMMICH_MINIO_SECRET_KEY
  dataFrom:
    - extract:
        key: immich-external-secret
