---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-v16-external-secret.yaml
  - ./cluster-v16.yaml
  - ./service.yaml
  - ./scheduled-backup.yaml
  - ./prometheus-rules.yaml
