# ########################################################################################################
# Trigger a manual backup with this resource.
# kubectl delete backup -n databases <backup-name>
# kubectl apply -f kubernetes/apps/databases/cloudnative-pg/clusters/manual-backups.yaml
# ########################################################################################################
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: postgresql-v17-backup
#   namespace: databases
# spec:
#   cluster:
#     name: postgresql-v17
#   method: plugin
#   pluginConfiguration:
#     name: barman-cloud.cloudnative-pg.io
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: immich-db-v17-backup
#   namespace: databases
# spec:
#   cluster:
#     name: immich-db-v17
#   method: plugin
#   pluginConfiguration:
#     name: barman-cloud.cloudnative-pg.io
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: postgresql-v16-backup
#   namespace: databases
# spec:
#   cluster:
#     name: postgresql-v16
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: immich-db-backup
#   namespace: databases
# spec:
#   cluster:
#     name: immich-db
