---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-v16
  namespace: databases
spec:
  schedule: "@daily"
  immediate: true
  suspend: false
  backupOwnerReference: self
  cluster:
    name: postgresql-v16

