---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-v17-scheduled-backup
  namespace: databases
spec:
  schedule: "@daily"
  immediate: true
  suspend: false
  backupOwnerReference: self
  cluster:
    name: postgresql-v17
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: postgresql-v16-scheduled-backup
#   namespace: databases
# spec:
#   schedule: "@daily"
#   immediate: true
#   suspend: false
#   backupOwnerReference: self
#   cluster:
#     name: postgresql-v16
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-v17-scheduled-backup
  namespace: databases
spec:
  schedule: "@daily"
  immediate: true
  suspend: false
  backupOwnerReference: self
  cluster:
    name: immich-db-v17
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: immich-db-scheduled-backup
#   namespace: databases
# spec:
#   schedule: "@daily"
#   immediate: true
#   suspend: false
#   backupOwnerReference: self
#   cluster:
#     name: immich-db
