---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-v17
  namespace: databases
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-standard-trixie
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgresql-objectstore
        serverName: &currBucketFolder postgresql-v17-2
  storage:
    size: 30Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: postgresql-superuser-secret
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "256MB"
      timezone: "America/Los_Angeles"
  monitoring:
    enablePodMonitor: true
  # ##########################################################################################################
  # Bootstrap a brand new cluster with a new app database and owner.
  # ##########################################################################################################
  # bootstrap:
  #   initdb:
  #     database: akash
  #     owner: akash
  #     secret:
  #       name: shared-db-external-secret

  # ##########################################################################################################
  # Bootstrap a new cluster from a backup in the *prevBucketFolder folder in the bucket.
  # ##########################################################################################################
  bootstrap:
    # Use this to recover a net-new cluster from a backup
    recovery:
      source: &prevBucketFolder postgres-v17-1
      # recoveryTarget:
      #   # Time base target for the recovery
      #   # targetTime: "2024-07-19 00:00:00.00000"
      #   targetLSN: "81/67000060"
  externalClusters:
    # This represents the s3 backup to restore from, the backup must be the same major version of the target cluster
    - name: *prevBucketFolder
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: postgresql-objectstore
          serverName: *prevBucketFolder

  # ##########################################################################################################
  # Bootstrap from an existing live cluster (same PostgreSQL major version)
  # ##########################################################################################################
  # bootstrap:
  #   pg_basebackup:
  #     source: postgresql-bitnami
  # externalClusters:
  #   # This must be the same PostgreSQL major version as the new cluster
  #   - name: postgresql-bitnami
  #     connectionParameters:
  #       host: postgresql-bitnami.databases.svc.cluster.local.
  #       user: postgres
  #     password:
  #       name: postgresql-superuser-secret
  #       key: password

  # ##########################################################################################################
  # Bootstrap from an existing live cluster (destination PostgreSQL major version higher than source)
  # monolith - Bootstrap the entire cluster
  # microservice - Bootstrap a single database
  # ##########################################################################################################
  # bootstrap:
  #   initdb:
  #     import:
  #       # type: microservice
  #       # databases:
  #       #   - "akash"
  #       # source:
  #       #   externalCluster: postgresql-bitnami
  #       type: monolith
  #       databases:
  #         - "*"
  #       roles:
  #         - "*"
  #       source:
  #         externalCluster: postgresql-v16
  # externalClusters:
  #   # This must be equal or higher PostgreSQL major version as the new cluster
  #   - name: postgresql-v16
  #     connectionParameters:
  #       host: postgresql-v16.databases
  #       user: postgres
  #     password:
  #       name: postgresql-superuser-secret
  #       key: password

