apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:o3OcR8F4G0Rj,iv:BT7ALJAfMC3KMzUkTXOKD4ORboR0lo9lP8tp3uvCCmY=,tag:WJzE+16//45x/p61o6dxqg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pz95efOCQ8uO6Ke16P/d87dqkc4BCg==,iv:yeTOt3gx+3zTFG/qZEjzwjYdxEvYXXFwGL4YBgcePds=,tag:UhF1ERqNL3HBWYylqavjZA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:h1pf7WrarpzF2D9UK/tNV/3JgH5cj/QYet4uCXwSnhMYSsbY,iv:u/qvwM2WDs3S1usjKGoa45JIH2lj/yuNOuEgBqUwNj0=,tag:adlzR2sImR8Nc4NAuCZdVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjhqdnpGQlB3Q2lBYjU1
            dnBrSStseW9RSkFBMzdDVUJrNlBUSUtUUFVVClovU1BIVU1kU2VEZGhVMG5pUi83
            RndGL1krUjB2dkVKNU5SbCtMY2lJN2sKLS0tIHN1NWxsZGFxTHZXTW1NNXpaUG9S
            VzM2aVIzOE9TYkZQSDlXVzFVbFY4bzAK3FnNZvbzjwrEV16/6piLDSp3Wm3YIeno
            6uxPP90hYlTc62D70qEERYOXIGugSjuOs8xvk0cpy8JZduMnSRMPpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T15:24:33Z"
    mac: ENC[AES256_GCM,data:vEjna5qnU9FvATPCHxrTnJejGNm+GKRoJvthA2dauirDdCLDH/TABdb92a0cOI46Yi/XQ4QoA+TtDxZYcMHUdleBLfTxzwzRhUZJKjrluupCklAGHt32uMDlWfHy/X0+pZDk5C83e8HTc5MJEUuUOBrTnLLj7BK6mQTGwhcTUVs=,iv:tiudpFiNDyEjdbWVG82Ulw06J/56T9vEQKkn4n5hDgA=,tag:3AaZhtCMxJCze2CQ3UiiZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
