---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app outline
  namespace: utilities
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: redis
      namespace: databases
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      outline:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret outline-external-secret
        initContainers:
          01-initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
            envFrom:
              - secretRef:
                  name: *secret
        containers:
          app:
            image:
              repository: outlinewiki/outline
              tag: 0.81.0
              pullPolicy: IfNotPresent
            env:
              NODE_ENV: "production"
              FILE_STORAGE: "local"
              FILE_STORAGE_LOCAL_ROOT_DIR: "/var/lib/outline/data"
              FILE_STORAGE_UPLOAD_MAX_SIZE: 104857600
              FILE_STORAGE_IMPORT_MAX_SIZE: 104857600
              FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE: 104857600
              LOG_LEVEL: "info"
              DEFAULT_LANGUAGE: "en_US"
              RATE_LIMITER_ENABLED: "true"
              RATE_LIMITER_REQUESTS: 1000
              RATE_LIMITER_DURATION_WINDOW: 60
              WEB_CONCURRENCY: 1
              ENABLE_UPDATES: "false"
              PORT: &port 3000
            envFrom:
              - secretRef:
                  name: outline-external-secret
    service:
      app:
        controller: outline
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "outline.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 10Gi
        retain: true
        advancedMounts:
          outline:
            app:
              - path: /var/lib/outline/data
                readOnly: false
