---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # outline
        SECRET_KEY: "{{ .OUTLINE_SECRET_KEY }}"
        UTILS_SECRET: "{{ .OUTLINE_UTILS_SECRET }}"
        URL: "https://outline.{{ .HOMELAB_SECRET_DOMAIN }}"
        DATABASE_URL: "postgres://{{ .OUTLINE_POSTGRESQL_USER }}:{{ .OUTLINE_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST_INTERNAL }}:{{ .POSTGRESQL_PORT }}/{{ .OUTLINE_POSTGRESQL_DBNAME }}"
        REDIS_URL: "redis://:{{ .REDIS_PASSWORD }}@{{ .REDIS_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_OUTLINE_DB }}"
        SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        SMTP_PORT: "{{ .HOMELAB_SMTP_PORT }}"
        SMTP_USERNAME: "{{ .HOMELAB_SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .HOMELAB_SMTP_PASS }}"
        SMTP_FROM_EMAIL: "{{ .HOMELAB_SMTP_USERNAME }}"
        SMTP_REPLY_EMAIL: "{{ .HOMELAB_SMTP_USERNAME }}"
        SMTP_SECURE: "true"
        OIDC_CLIENT_ID: "{{ .OUTLINE_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OUTLINE_OIDC_CLIENT_SECRET }}"
        OIDC_AUTH_URI: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/authorize/"
        OIDC_TOKEN_URI: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/token/"
        OIDC_USERINFO_URI: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/userinfo/"
        OIDC_LOGOUT_URI: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/outline/end-session/"
        OIDC_USERNAME_CLAIM: "preferred_username"
        OIDC_DISPLAY_NAME: "Authentik"
        OIDC_SCOPES: "openid profile email"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .OUTLINE_POSTGRESQL_DBNAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .OUTLINE_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .OUTLINE_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: outline-external-secret
