---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./n8n/ks.yaml
  - ./openwebui/ks.yaml
  - ./node-red/ks.yaml
  - ./windmill/ks.yaml

