---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appflowy-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # appflowy cloud
        RUST_LOG: "info"
        APPFLOWY_ENVIRONMENT: "production"
        APPFLOWY_ACCESS_CONTROL: "true"
        APPFLOWY_GOTRUE_JWT_SECRET: "{{ .APPFLOWY_JWT_SECRET }}"
        APPFLOWY_GOTRUE_JWT_EXP: "7200"
        APPFLOWY_WEBSOCKET_MAILBOX_SIZE: "6000"
        APPFLOWY_DATABASE_MAX_CONNECTIONS: "40"
        APPFLOWY_DATABASE_URL: "postgres://{{ .APPFLOWY_POSTGRESQL_USER }}:{{ .APPFLOWY_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST_INTERNAL }}:{{ .POSTGRESQL_PORT }}/{{ .APPFLOWY_POSTGRESQL_DBNAME }}"
        APPFLOWY_REDIS_URI: "redis://:{{ .REDIS_PASSWORD }}@{{ .REDIS_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_APPFLOWY_DB }}"
        APPFLOWY_MAILER_SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        APPFLOWY_MAILER_SMTP_PORT: "{{ .HOMELAB_SMTP_PORT }}"
        APPFLOWY_MAILER_SMTP_USERNAME: "{{ .HOMELAB_SMTP_USERNAME }}"
        APPFLOWY_MAILER_SMTP_PASSWORD: "{{ .HOMELAB_SMTP_PASS }}"
        APPFLOWY_S3_USE_MINIO: "true"
        APPFLOWY_S3_MINIO_URL: "http://minio.storage:9000"
        APPFLOWY_S3_ACCESS_KEY: "{{ .APPFLOWY_MINIO_ACCESS_KEY }}"
        APPFLOWY_S3_SECRET_KEY: "{{ .APPFLOWY_MINIO_SECRET_KEY }}"
        APPFLOWY_S3_BUCKET: "appflowy"
        # appflowy admin frontend
        ADMIN_FRONTEND_REDIS_URL: "redis://:{{ .REDIS_PASSWORD }}@{{ .REDIS_HOST }}:{{ .REDIS_PORT }}/{{ .REDIS_APPFLOWY_DB }}"
        ADMIN_FRONTEND_GOTRUE_URL: "http://gotrue:9999"
        ADMIN_FRONTEND_APPFLOWY_CLOUD_URL: "http://appflowy_cloud:8000"
        # appflowy gotrue
        API_EXTERNAL_URL: "https://appflowy.{{ .HOMELAB_SECRET_DOMAIN }}"
        GOTRUE_DB_DRIVER: "postgres"
        DATABASE_URL: "postgres://{{ .APPFLOWY_POSTGRESQL_GOTRUE_USER }}:{{ .APPFLOWY_POSTGRESQL_GOTRUE_PASS }}@{{ .POSTGRESQL_HOST_INTERNAL }}:{{ .POSTGRESQL_PORT }}/{{ .APPFLOWY_POSTGRESQL_DBNAME }}"
        GOTRUE_JWT_SECRET: "{{ .APPFLOWY_JWT_SECRET }}"
        GOTRUE_JWT_EXP: "7200"
        GOTRUE_RATE_LIMIT_EMAIL_SENT: "10"
        GOTRUE_EXTERNAL_GOOGLE_ENABLED: "false"
        GOTRUE_EXTERNAL_GITHUB_ENABLED: "false"
        GOTRUE_EXTERNAL_DISCORD_ENABLED: "false"
        GOTRUE_MAILER_URLPATHS_CONFIRMATION: "/gotrue/verify"
        GOTRUE_MAILER_URLPATHS_INVITE: "/gotrue/verify"
        GOTRUE_MAILER_URLPATHS_RECOVERY: "/gotrue/verify"
        GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "/gotrue/verify"
        GOTRUE_SMTP_HOST: "{{ .HOMELAB_SMTP_HOST }}"
        GOTRUE_SMTP_PORT: "{{ .HOMELAB_SMTP_PORT }}"
        GOTRUE_SMTP_USER: "{{ .HOMELAB_SMTP_USERNAME }}"
        GOTRUE_SMTP_PASS: "{{ .HOMELAB_SMTP_PASS }}"
        GOTRUE_SMTP_ADMIN_EMAIL: "{{ .HOMELAB_ADMIN_EMAIL }}"
        GOTRUE_ADMIN_EMAIL: "{{ .APPFLOWY_ADMIN_EMAIL }}"
        GOTRUE_ADMIN_PASSWORD: "{{ .APPFLOWY_ADMIN_PASSWORD }}"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        # appFlowy AI
        # APPFLOWY_AI_OPENAI_API_KEY: ""
        # APPFLOWY_AI_SERVER_PORT: "5001"
        # APPFLOWY_AI_SERVER_HOST: "ai"
        # APPFLOWY_AI_DATABASE_URL: "postgresql+psycopg://postgres:password@postgres:5432/postgres"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .APPFLOWY_POSTGRESQL_DBNAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .APPFLOWY_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .APPFLOWY_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: redis-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: appflowy-external-secret
