---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appflowy
  namespace: utilities
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: redis
      namespace: databases
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      appflowy:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret appflowy-external-secret
        initContainers:
          01-initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
            envFrom:
              - secretRef:
                  name: *secret
        containers:
          appflowy-cloud:
            image:
              repository: appflowyinc/appflowy_cloud
              tag: 0.5.28
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secret
          gotrue:
            image:
              repository: appflowyinc/gotrue
              tag: 0.5.28
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secret
          admin-frontend:
            image:
              repository: appflowyinc/admin_frontend
              tag: 0.5.28
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secret
          # ai:
          #   image:
          #     repository: appflowyinc/appflowy_ai
          #     tag: 0.5.13
          #     pullPolicy: IfNotPresent
          #   envFrom:
          #     - secretRef:
          #         name: *secret
          nginx:
            image:
              repository: nginx
              tag: stable
    service:
      app:
        controller: appflowy
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "appflowy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      nginx-config:
        enabled: true
        type: configMap
        name: appflowy-nginx-config
        advancedMounts:
          appflowy:
            nginx:
              - path: /etc/nginx/nginx.conf
                subPath: nginx.conf
                readOnly: true
