# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app onepassword-connect
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret onepassword-connect-secret
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
        containers:
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.7.2
            env:
              OP_BUS_PORT: "11221"
              OP_BUS_PEERS: "localhost:11220"
              OP_HTTP_PORT: &port1 8081
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: onepassword-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port1
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port1
                  initialDelaySeconds: 15
              startup:
                enabled: false
          main:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.7.2
            env:
              OP_BUS_PORT: "11220"
              OP_BUS_PEERS: "localhost:11221"
              OP_HTTP_PORT: &port2 8080
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: onepassword-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port2
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port2
                  initialDelaySeconds: 15
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *port2
    ingress:
      main:
        enabled: true
        primary: true
        className: internal
        hosts:
          - host: &host "onepassword-connect.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      shared:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /home/opuser/.op/data
            readOnly: false

