---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app onepassword-connect
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: external-secrets
      namespace: security
  values:
    controllers:
      onepassword-connect:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret onepassword-connect-secret
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
        containers:
          app:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.7.3
            env:
              XDG_DATA_HOME: &configDir /config
              OP_BUS_PORT: 11220
              OP_BUS_PEERS: localhost:11221
              OP_HTTP_PORT: &apiPort 8080
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: onepassword-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *apiPort
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *apiPort
                  initialDelaySeconds: 15
              startup:
                enabled: false
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.7.3
            env:
              XDG_DATA_HOME: *configDir
              OP_BUS_PORT: 11221
              OP_BUS_PEERS: localhost:11220
              OP_HTTP_PORT: &syncPort 8081
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-connect-secret
                    key: onepassword-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *syncPort
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *syncPort
                  initialDelaySeconds: 15
              startup:
                enabled: false
    service:
      app:
        controller: onepassword-connect
        ports:
          http:
            port: *apiPort
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "onepassword-connect.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      shared:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: *configDir
            readOnly: false

