apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WBOZoBM2kMnNqgwK5ep6stUN7DWfBpe7cJtFyyeLV1w=,iv:O3tgD1RPpmjjShowfvCx5rKaUU0oHGXBAkj5iu0FWTQ=,tag:PpIWA7yZrQaoQR2YVtV4Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWjBlOXVyb2NrNE9Memsz
            MDVaVXNQeG5TUkpDQldrY3FZbTJZTWVxNzBRCmpuS0NVTW1xUGZkSUVzeC9vSUdB
            NnI3UUgzRzViUmdhWHV2UXhkeVE4TUkKLS0tIDhtTXFKQ0gvK0RTZzg3N3YvUk13
            VDBEVUU2MnFxL2RVT2xoN0t0RTlNUHcKopzbYRcYP2QOlTOgMFzcE2SK/qvWYDdt
            XbuayPQZSsD/pGH55u8d98kHH3WkQi2D+qTSB/h09JFEntPAFf9wjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T23:07:55Z"
    mac: ENC[AES256_GCM,data:vNZKNwrQqEvIQBl4Fg5FDwxnYXSregVFimBRPVbZuiB/CR9XPGxwp0gBUoqJxHVZDqbKCWWFDeZX5EQBaTfQEs5cycZnnq59GSsChphByjhq3jMngtslrLw/009nT3dHSJ/RiXDawUDt8ZgT+oHOahVd5AQCye0M3BIkGLq25QE=,iv:dI7QDnTd/riBN12xBv0sRZbfER0CMvYqYoOVN3t2CTs=,tag:NXAR8CmSSuCBWaDyKsKL+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
