apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9Bch+vxG1QjzNeW1iGIGp9RnMIQ94jayrSqoXscJdnY=,iv:xnNAlh1avXRVyVoUtBC7jUR0skIgq0bfIfOpFrTciSM=,tag:B+DlF+pEs4wr672E29Q2rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZklRNjJWNFlLeEMwcXd4
            WGNLdU9tdDB2TlgxNDg5b3VqSGJqYUVDNTJzCmZTSTBlM29PYzQ0U053OER2d2l4
            OERRVXB6R3hkOUhmc0YyUnVjamZuU2sKLS0tIGF1djNyZG1oZDRJaVlIcWs5cjVt
            NUpqV01qeUNYNTl0WEhpS2NKZ0ErZlUKhzugUrZ/L+YBDImWcEd7X63pLjH3jpdP
            bfy90+wpYs8BcSHI2wd+qElonIhxDBGcHahkWRNXF0vOjAawkBFvNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T05:52:11Z"
    mac: ENC[AES256_GCM,data:ZpdaAXXoax2wBIEncKNgCSUjXFs9cSHybTWUx4CYk/lRpk/sUfpw49JkeK/6Yd+Z0/cNJr/ijI9c5iIB0UdnwCV/7OhnrV/9NMZ+XyolwlP+g4ArNuyfsDxCuybW8FTaLoDO357QmlosglT9jkySuje187NrTvsqGhA7bd8qVLQ=,iv:S9CU1vilWo/P8C9V01Oh5ilPqONZLdGWUQpKzYNqdvw=,tag:DXwPL/YiEdC4k2799CuRaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
