apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Q/mGTDG4aDneQyhjv5c72n778jzUPFqIROqJEifAcgs=,iv:ntQ9F3yc84e3j74rIKWMaENPn4d84NUAO4lgnj0dbKA=,tag:uij7dEP9250IBvBlTqpd+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYzliVHV2Qmh6YlFpNGtl
            MmdSSWE2dlR4NTVXL1N2c0JpcWNMbmVBVm5NCmJxQkVDQ2lFcWhDdENTTERuazZm
            OTd5NkhWRURta2VoNG5NYUhqTjVTS1UKLS0tIDdkRlRwL0JWVkNCOXlJU1kydjlo
            SFpVdE9nVWRDa2IyYVhUMVFvTFJJVm8K9+ajipioLAyqsud0UlNG98zJtox6El5p
            zH1EjCw9Uc8Z0Pz6Oxnm0WobjbWrcbomIXBDbaBfwppOK0qJoGgraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T06:05:31Z"
    mac: ENC[AES256_GCM,data:TolxXRNMLbE/tr9ExTGEL+YBfPqpnCDfPsrZoygYw4DtEpBzaelt2Y93dzGJnoGHkGgpoeBSVrW4j1ssoSf2P+CmZjEH05yZ72VSbMhENye6iAPn6J9n5bWyZ1/baHcDKIa4RCTNOINpqm/UVIDu++GeynXJHpS9semGLZl8zFU=,iv:k3FQG4CFOsT7NHnmB21IT4sq6cJULq0DNO/DoRBjKXc=,tag:crAsABhLGs1wmHg/wGqoBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
