---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: immich-db-backup
  namespace: media
spec:
  cluster:
    name: immich-db
# ########################################################################################################
# Trigger a manual backup with this resource.
# kubectl delete backup -n media immich-db-backup
# kubectl apply -f kubernetes/apps/media/immich/app/database/manual-backup.yaml
# ########################################################################################################
