---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-scheduled-backup
  namespace: databases
spec:
  schedule: "@daily"
  immediate: true
  suspend: false
  backupOwnerReference: self
  cluster:
    name: immich-db
