---
apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich-db.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: "${LB_IMMICH_DB_ADDRESS}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich-db
    role: primary
