---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    recommender:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 100M
        limits:
          memory: 200M
      extraArgs:
        storage: prometheus
        prometheus-address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    updater:
      enabled: false
    admissionController:
      enabled: false
