---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: unifi
      namespace: networking
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      unpoller:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret "unpoller-external-secret"
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.11.2@sha256:73b39c0b3b8fa92aa82a7613d3486253ffbd8c057833b4621402a268159bf2a2
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              limits:
                cpu: 100m
                memory: 128M
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 9130
    serviceMonitor:
      app:
        serviceName: unpoller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
