---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: unifi
      namespace: networking
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      unpoller:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret "unpoller-external-secret"
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.14.1@sha256:9ba73b1793ef332ae9b4b719ef0fc09f231d6276bc7b721cbb47961ed7792961
            envFrom:
              - secretRef:
                  name: *secret
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 9130
    serviceMonitor:
      app:
        serviceName: unpoller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
