---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./windmill-external-secret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
configMapGenerator:
  - name: windmill-grants
    namespace: automation
    files:
      - ./scripts/grants.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
