---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: windmill-external-secret
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # windmill
        WINDMILL_POSTGRES_URL: "postgres://{{ .WINDMILL_POSTGRESQL_USER }}:{{ .WINDMILL_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST }}/{{ .WINDMILL_POSTGRESQL_DB }}"
        # postgres init
        INIT_POSTGRES_DBNAME: "{{ .WINDMILL_POSTGRESQL_DB }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_USER: "{{ .WINDMILL_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .WINDMILL_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: windmill-external-secret
