---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./helmrelease.yaml
  - ./node-red-external-secret.yaml
# configMapGenerator:
#   - name: node-red-configmap
#     files:
#       - ./resources/settings.js
# generatorOptions:
#   disableNameSuffixHash: true
