---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-red-external-secret
  namespace: automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # node-red
        NODE_RED_CREDENTIAL_SECRET: "{{ .NODE_RED_CREDENTIAL_SECRET }}"
        NODE_RED_OAUTH_CLIENT_ID: "{{ .NODE_RED_OAUTH_CLIENT_ID }}"
        NODE_RED_OAUTH_CLIENT_SECRET: "{{ .NODE_RED_OAUTH_CLIENT_SECRET }}"
        NODE_RED_OAUTH_ISSUER_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/node-red/"
        NODE_RED_OAUTH_AUTH_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/authorize/"
        NODE_RED_OAUTH_TOKEN_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/token/"
        NODE_RED_OAUTH_USER_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/userinfo/"
        NODE_RED_OAUTH_CALLBACK_URL: "https://nodered.{{ .HOMELAB_SECRET_DOMAIN }}/auth/strategy/callback/"
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: node-red-external-secret
