---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    controllers:
      unifi:
        type: statefulset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jacobalberty/unifi
              tag: v9.1.120
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE: null
              JVM_MAX_HEAP_SIZE: 1024M
              TZ: "${TIMEZONE}"
    service:
      app:
        controller: unifi
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: "${LB_UNIFI_ADDRESS}"
        ports:
          # Web admin
          http:
            port: 8443
          # device communication
          device-comm:
            enabled: true
            port: 8080
            protocol: TCP
          # STUN
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # AP discovery
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
          # 'Make controller discoverable on L2 network' option
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
          # UniFi mobile speed test
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
          # Remote syslog port
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          # HTTPS portal redirection
          guest-portal-https:
            enabled: true
            port: 8843
            protocol: TCP
          # HTTP portal redirection
          guest-portal-http:
            enabled: true
            port: 8880
            protocol: TCP
          # DNS TCP
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
          # DNS UDP
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
          # NTP (date and time)
          ntp-udp:
            enabled: true
            port: 123
            protocol: UDP
          # local-bound database communication
          local-db:
            enabled: true
            port: 27117
            protocol: UDP
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: unifi-pvc
        globalMounts:
          - path: /unifi
            readOnly: false
