---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    controllers:
      unifi:
        type: statefulset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jacobalberty/unifi
              tag: v8.3.32
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE: null
              JVM_MAX_HEAP_SIZE: 1024M
              TZ: "${TIMEZONE}"
            resources:
              limits:
                cpu: 500m
                memory: 2Gi
    service:
      app:
        controller: unifi
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${LB_UNIFI_ADDRESS}"
        ports:
          # Web admin
          http:
            port: 8443
          # device communication
          device-comm:
            enabled: true
            port: 8080
            protocol: TCP
          # STUN
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # AP discovery
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
          # 'Make controller discoverable on L2 network' option
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
          # mobile throughput test
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
          # Remote syslog port
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          # guest portal redirect ports
          guest-portal-https:
            enabled: false
            port: 8843
            protocol: TCP
          guest-portal-http:
            enabled: false
            port: 8880
            protocol: TCP
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: unifi-pvc
        globalMounts:
          - path: /unifi
            readOnly: false
