apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:g5sYCSdS0ACoaGvDshkcZkElHI9jcxRpSbTvgdIFgOA1keFN/xs6Xg==,iv:IjesS/d0RgWQylFknahEVYTD4Hv/SUiU8TbJroFDzFQ=,tag:78UOEQciGC/A38xgguMhIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZmVpMXFqTnRTdEZweHFu
            L0xhekRrVUxQTERRMERkZ3VFYlI0OTRZUkI0CkpzODdGbDk2Y3IxUTVKMEtTWW8v
            TksyWGJjcWV6ajl2MWpUUE54WnlINU0KLS0tIFdqbXkreGs2U0JES3NHL1JHQzd4
            bVNjUk15WnFRc1ltK0NveHRXWUhnZjQKRR2NEcoKMBQKHdUVVTrBi2zQlEz/TXDS
            de8f54g53zC5VQv1aiD7EtfwbFiDiZ9e+7KBOnWX2aryDHZnEXXneA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-26T22:30:46Z"
    mac: ENC[AES256_GCM,data:QDvPUHKK3LOPd9RpGYLt1Y3AyI2wDNTKhX4u3TLBXw7TYOIdnCWsH5YJjnsBdySd+UKG4q8w7S/ZtXDoQ9TTtmOvQlqIKMSXMLYnYeD1Mv51l8asNKfaS8SgB+om8A9aLiuBzkQYd3+881tEPAS23UdpCIWmDQEur/v14HgqUzQ=,iv:5pEBt7KFDxaKmwGRm4FBXXtVqIShCAVw6Io89aBbHes=,tag:/t85XensYPigzDqUP8i3pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
