# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:xWy6YDv/2bAPskEz57s2t/laxDzFzFNAYEyNK+5TUfy+RIgX2FLl3g==,iv:LQ+dKQY1me/Ku8lVVqrpRiT8S0Ll6RHLzNRJ2pyaK90=,tag:NNa054Ub/zHHTBDnCdjjdg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNkQ3TnNxUjVjWU5lSk0v
        cDQyQTQ4eVd2MlFpT1kyY29JMjJEQSthUXhBCm0xZHlkVlBVaTdIaTd2YWIvQy9I
        bDFZamdCcURIMElWSng2K2w4UG4xOU0KLS0tIG1BS3FzUS93N0hZd2d2Q2lCbEty
        NTR1eCtvUnpvZDFvcXR3dHhYcEhpRDQKhLF3DqlK8QvGJDuxQ+ieOfzyo8QNS6Ej
        AD6rVg6EtHNjFtc5tBRLXNJ4QzpgbbcH+klZkQMUQY9mzEOSrRBXiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T02:36:19Z"
  mac: ENC[AES256_GCM,data:LSSXytuJuWwHmUY4X25nqTnXOqb/2GHt7hxq2UA3cwiB5zNBEjMUAwaeL8Cldsx3YA+7qCz3L9cr8K4wBX0/EwYb2aENvVcWtlQiluzq+L2ejTEhpEq3v2wUdPujGq2LKaWJpz7lDsHIlMyS+o+W9twSOpxuMigKaK/hGPk1HLk=,iv:ZrkZwSqA77cJVD4uqMm0F5FdXEOQQ1qxjD5fS6yJhdU=,tag:qnePb4GpreLkaNZHU9WvPA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.2
