apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Ynvj9BV+JHDFSLgYm4mkwNGswGAw/JlOiJRACMSy2XFD1/LZL39/nA==,iv:jee4lyq92rKCSf0kCSdY/JfHhgImnmUyBQTUnbn0FoI=,tag:NDyD2h+BTLXgqUm8M5HnxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMTREQkVNMGpaZjBPU2pR
            WHA0bkQyaVdhdnZWVTlKTDA3ZFdLMzFrUUN3CjRMNFVudjVLY1h5MHRMZ1JQYnJD
            bm5WeVFhb1dhWWwrZk14VHBiM1J2VE0KLS0tIDMraWJVaFcrZXZEL01lMGtRQjYy
            dTY0RUdlWWpYZFpyMHNNcTd5NnNiM3MK3vc/SyTjcEK14TYwha/aLTx2dERB7oAw
            2PdyBAcL3xs2O/cxzSVwfVeGgqkgFfs0LiA86CeKC7mNHabBWdNimQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T05:55:34Z"
    mac: ENC[AES256_GCM,data:ahB2jhXeMI5CH1yVOuspomIGsykWe0vZI/Mxbkyjmpntbl3BxXwY6QjXoBt0kC7kLJBgkpj1MJcH2YLds5H3AgiTv+iXcLSfl/vhxdp62bVQi6Sqvfl0CMtCHRzyI+aEzpI4H+bJI810mAUpK6/mYMtzkKKa4zFuG9Jm2MK7yxY=,iv:piOXyVA/XT9/eOOPS6cig2STJXFkXpHDuJuFO32AFQ8=,tag:u8qYHxIUSn5ZX9woQNx0zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
