apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3bLYQLftHBXg0HTMBBRTeeNDcGvRfSsiadRGxZjwKreU71IKBEM8EA==,iv:DAYdQmUAX2iAm/OYf/H/s3rIXh6RzSOt6YuhR/bzB0c=,tag:O/dOgCRmClg0X00BPNvygA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnst27uc8fh8kwjfql87hcz5xv84d0plgue966a0cdeh34v7taqqg9xngq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWnZlTTZoMFk1NE1KdDRG
            WTlKb2dRV3VJSUNMb2pocDdpUzlXQmVJNVRrCndvbmNjNXhtTnZ2R2pHMDBHK3dJ
            aWRJMUNoVi95ZkU5bTh3cTU5aUoyNGcKLS0tIGhEaWFCT1RvUkJoTk4rdHE1NHQx
            ZVhWRnA4ZGczMjlFZTNYOW53ODNxOVUKtkZUQeRHHOUyDTDrMEjdglabtSAzgINk
            WFzoiBkJWgFASTF8UQiQ5ItCegTxUIhpkV0ebhJmWOYblqpxsN7AMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T03:53:21Z"
    mac: ENC[AES256_GCM,data:GJQwAalEbm47kPtPwm5jcroZNUvnMyAfPCibsj0ff3d5f6x/YbcsB+DbgvMEfQxqeQ03QFmoedrB18OaUdvJzwVoEOsQ1PxHhitHRyZbpgTEQ5gonVDbyHhlzqctpq3/IRZXb5bDXZWJm2M87gpBrWt/CvCPVFqDq5y8+zyAQm0=,iv:J5TlffgA9kVMd8URIoSaUQzeTPVXcWMDYclEdFFHCgE=,tag:FaM4pW3zfGRWyB3N4GDsBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
