---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # miniflux
        ADMIN_USERNAME: "{{ .MINIFLUX_ADMIN_USER }}"
        ADMIN_PASSWORD: "{{ .MINIFLUX_ADMIN_PASS }}"
        DATABASE_URL: "postgres://{{ .MINIFLUX_POSTGRESQL_USER }}:{{ .MINIFLUX_POSTGRESQL_PASS }}@{{ .POSTGRESQL_HOST }}/{{ .MINIFLUX_POSTGRESQL_DB }}?sslmode=disable"
        OAUTH2_PROVIDER: "oidc"
        OAUTH2_CLIENT_ID: "{{ .MINIFLUX_OIDC_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .MINIFLUX_OIDC_CLIENT_SECRET }}"
        OAUTH2_REDIRECT_URL: "https://miniflux.{{ .HOMELAB_SECRET_DOMAIN }}/oauth2/oidc/callback"
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/miniflux/"
        # postgres init
        INIT_POSTGRES_HOST: "{{ .POSTGRESQL_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .MINIFLUX_POSTGRESQL_DB }}"
        INIT_POSTGRES_USER: "{{ .MINIFLUX_POSTGRESQL_USER }}"
        INIT_POSTGRES_PASS: "{{ .MINIFLUX_POSTGRESQL_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRESQL_SUPERUSER_PASS }}"
  dataFrom:
    - extract:
        key: postgresql-external-secret
    - extract:
        key: homelab-external-secret
    - extract:
        key: miniflux-external-secret
