---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoarder-external-secret
  namespace: utilities
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        # hoarder
        NEXTAUTH_SECRET: "{{ .HOARDER_NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .HOARDER_MEILI_MASTER_KEY }}"
        OPENAI_API_KEY: "{{ .HOARDER_OPENAI_API_KEY }}"
        OAUTH_WELLKNOWN_URL: "https://auth.{{ .HOMELAB_SECRET_DOMAIN }}/application/o/hoarder/.well-known/openid-configuration"
        OAUTH_CLIENT_ID: "{{ .HOARDER_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .HOARDER_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: homelab-external-secret
    - extract:
        key: hoarder-external-secret
